### ISSUE TITLE
Benchmarking harnesses for measuring cost analysis constants

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#1165]

**Comment by jcnelson** [comment]
Will test on a wimply AWS node.  Miners are expected to have SSDs, but nodes aren't.

**Comment by diwakergupta** [comment]
@kantai @reedrosenbluth can this be closed?

**Comment by reedrosenbluth** [comment]
> @kantai @reedrosenbluth can this be closed?

Shouldn't be closed, but it's no longer a mainnet blocker. I'll remove that label.

**Comment by diwakergupta** [comment]
@reedrosenbluth @pavitthrap isn't this addressed by the work y'all are doing? In case maybe we can mark it done or in-progress vs. stale

**Comment by jcnelson** [comment]
This has shipped
