### ISSUE TITLE
Reference Clarity as a language on Github 

### ISSUE THREAD

**Issue by lgalabru** [stacks-network/stacks-blockchain#1253]
Not mission critical today, but probably a quick win in terms of Developer Experience.
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

**Comment by diwakergupta** [comment]
Unlikely Github would accept a new language without established prior usage on Github. Nonetheless, we can try. Probably best for DevX to take this on though cc/ @agraebe . If that sounds good, I can move this to another relevant repo.

**Comment by agraebe** [comment]
wasn't someone from growth working on this already? is this ticket a duplicate? @cuevasm @jdbender66 ?

**Comment by lgalabru** [comment]
@jdbender66 do you think that this is something that can be done now?

**Comment by lgalabru** [comment]
Addressed! https://media.discordapp.net/attachments/713087894260023377/946170638865956864/unknown.png

**Comment by jcnelson** [comment]
Rejoice :tada:
