### ISSUE TITLE
Add `mine_block` RPC endpoint

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#1420]
Add an authenticated/development/localhost RPC endpoint to force a block mine. See [`evm_mine` eth RPC for inspiration](https://github.com/trufflesuite/ganache-cli#custom-methods).

Development and testing environments needs more control of blockchain progression -- examples:
* A public regtest explorer with a faucet, contract deploy, and contract call playground endpoints; I want this environment to perform regular mining at something like 0.5-10 minute intervals, but have submitted transactions trigger an immediate mine. 
* An integration testing environment that needs fine-grained control over tx minting.

**Comment by jcnelson** [comment]
> Add an authenticated/development/localhost RPC endpoint to force a block mine. See evm_mine eth RPC for inspiration.

Just so you know, going forward, Stacks nodes won't directly mine blocks.  Instead, there will be a separate miner program that generates and broadcasts the requisite Bitcoin transactions, and propagates the Stacks block.  The Stacks node will implement a `get_block_template`-like API endpoint that generates and returns a block built from unconfirmed transactions, as well as some metadata like the block's hash and (possibly) a template block-commit Bitcoin transaction for the miner to sign.

**Comment by zone117x** [comment]
The Clarity SDK still needs this feature from the mocknet node, e.g. to complete this feature https://github.com/blockstack/clarity-js-sdk/pull/83/files

**Comment by zone117x** [comment]
Not sure if this is stale now that @lgalabru is maintainer of the project used for Stacks+Clarity testing (Clarinet). I used write a lot of smart contract tests that required this feature -- @lgalabru is this still needed?

**Comment by jcnelson** [comment]
I think the consensus around this is that mining is a separate process from the node.  Please reopen if we want to revisit this.
