### ISSUE TITLE
Reconcile Principal Type IDs

### ISSUE THREAD

**Issue by reedrosenbluth** [stacks-network/stacks-blockchain#1450]
Principals have different Type IDs depending on if they are being serialized in a Post Condition, or as a Clarity Value. Would it be possible to make these IDs the same?

**Comment by jcnelson** [comment]
Even if we did, the serialization wouldn't be the same.  Postconditions aren't represented as Clarity values in the first place.

**Comment by kantai** [comment]
We could make the principal serializations the same, though. That way, there'd only be one way to represent a principal -- I think we'd just need to change the PostConditionPrincipalID to be something like

0x00 => Origin
0x05 => Standard Principal
0x06 => Contract

**Comment by jcnelson** [comment]
I'm open to making principal serializations the same in both.  Want to send a PR?

**Comment by kantai** [comment]
This still should be implemented.

**Comment by kantai** [comment]
Closing this -- the post condition principal type IDs weren't changed before Stacks 2.0 and we haven't received much pushback on their current values. If this becomes a pain point in the future, this could be revisited as a potential consensus breaking change.
