### ISSUE TITLE
Revisit MARF sentinel hash usage

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#1561]
We currently use the sentinel hash in our codebase in at least two different ways, and I think that's led to at least one problem, and could bite us again down the road -- the two ways are:

1. It indicates that the TrieFileStorage is currently not "opened" to a block.
2. It is used as the parent of the first mined block.

I'd suggest as a first step, replacing the first case with an Option.

**Comment by jcnelson** [comment]
To clarify, you're suggesting we replace the `TrieFileStorage` instance in the `MARF` as an `Option<TrieFileStorage>`?

**Comment by kantai** [comment]
No, that should maybe be done as well, though. I'm suggesting that `TrieFileStorage.cur_block` be implemented as `Option<BlockHeaderHash>`, much like `cur_block_id` is an `Option<u32>` -- in fact, `cur_block` and `cur_block_id` should probably be an `Option<(BlockHeaderHash, u32)>`, since they should always have the same Some/None states.

**Comment by jcnelson** [comment]
Gotcha.  That sounds reasonable to me.

**Comment by kantai** [comment]
This would still be a useful refactor!

**Comment by jcnelson** [comment]
This is now in `master`.
