### ISSUE TITLE
P2P: UPnP support for Stacks nodes

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#1753]
At some point, we will want it to be possible for Stacks nodes to register themselves on home networks and serve blocks and transactions to not only local clients, but also to public clients beyond the NAT.  But to do that automatically, the Stacks node needs to implement enough of the UPnP protocol in order to set up port-forwarding rules for itself on the home router.

**Comment by zone117x** [comment]
Not stale. This is important for the health of the network. Some blockchains use https://github.com/miniupnp/miniupnp with success. I haven't had luck finding robust rust libs yet.

**Comment by jcnelson** [comment]
Temporarily assigning to @zone117x so this has an owner. Please feel free to re-assign as you see fit.

I'm not sure this issue is necessary?  The network code already gives NAT'ed nodes the ability to:

* announce neighbors to upstream peers
* serve blocks, microblocks, and transactions to upstream peers 
* (future) serve StackerDB data to upstream peers

In other words, I think the network protocol removes the need for a user to punch a hole in their NAT.  If you agree, please feel free to close.
