### ISSUE TITLE
[TESTNET BUG] map_entry api returns "none" data for non-existing contracts

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-blockchain#1865]
## Describe the bug

The endpoint for `map_entry` returns a 200 response even though the url refers to a non-existing contract or non-existing map

## Steps To Reproduce

1. Make a "POST" call to `http://testnet-master.blockstack.org:20443/v2/map_entry/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV/monsters-invalid-contract/monsters-invalid-map` with data `"0x0100000000000000000000000000000001"`, e.g. with curl
```
curl -X POST -H 'Content-Type: application/json' -i 'http://testnet-master.blockstack.org:20443/v2/map_entry/ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV/monsters-invalid-contract/monsters-invalid-map' --data '"0x0100000000000000000000000000000001"'
```
2. See result `{"data":"0x09","proof":""}`

## Expected behavior

Should return a 404 response if the address, contract or map does not exist

## Environment

 - OS: [e.g. Ubuntu / Debian]
 - Rust version
 - Output of `stacks-node version`

## Additional context

Please include any relevant stack traces, error messages and logs.

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by friedger** [comment]
It looks like that "none" data is returned for valid path and body as well

**Comment by friedger** [comment]
@timstackblock is there any app that makes use of this api?

**Comment by timstackblock** [comment]
Thanks for bringing this up @friedger let me look into this

**Comment by diwakergupta** [comment]
@lgalabru can you confirm if this is expected behavior or a bug? If latter, perhaps @reedrosenbluth can take a stab -- from the description it sounds like it might be a simple fix.

**Comment by lgalabru** [comment]
Sounds like a good api improvement / bug fix.

**Comment by timstackblock** [comment]
@lgalabru just following up to see if there is any update on this bug
