### ISSUE TITLE
Fees: Convert transaction cost to a dimensionless fill value

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#1886]
We need to come up with a way to convert a transaction's measured cost into a single dimensionless fill value _F_, between 0.0 and 1.0, that represents the portion of the block's total compute budget consumed.  Once we can do this, then we can assess transaction fees as `fee_rate * F`.

Now, I _think_ that the following properties hold.  Please correct me if I'm wrong:
* The unit costs for `read_count` and `write_count` are _O(1)_ -- doing a single MARF read or write is _O(1)_
* The unit costs for `read_length` and `write_length` are _O(1)_ -- reading or writing a single byte is _O(1)_ [1]
* The unit cost for `runtime` is _O(1)_ -- each atomic unit of work in the Clarity VM is _O(1)_

If so, then we can represent the cost conversion as simply taking the inner product between the transaction cost (a 5-element vector _C_) and the constant conversion vector (a 5-element vector _P_) to get the transaction's total fill _F).  The VM would continue to enforce the total cost of each block in terms of the maximum amount of each resource dimension a block can occupy (represented by `ExecutionCost`), but transaction fee assessment would be calculated with respect to _F_.

[1] Reading/writing data in Sqlite3 is technically _O(n log n)_ for _n_ rows in a table, but this is an implementation artifact that comes with using Sqlite3.  We treat Sqlite3 like an on-disk hash table, so we should assess costs on reading/writing to it as such.

**Comment by jcnelson** [comment]
Estimated time to write and test: 3 days
Estimated time to review the PR: 1 day

**Comment by lgalabru** [comment]
I think this was addressed, @kantai can we close?

**Comment by kantai** [comment]
I don't think we can close -- this was tabled for Stacks 2.0 release, but may be tabled for 2.1.

**Comment by jcnelson** [comment]
I'm not sure we're going to do this after all.
