### ISSUE TITLE
Streamline burnchain block height types

### ISSUE THREAD

**Issue by lgalabru** [stacks-network/stacks-blockchain#1931]
I've noticed some type discrepancy between this 2 structs:

```
pub struct BurnchainBlockHeader {
    pub block_height: u64,
    ...
} 
```

and 

```
pub struct StacksHeaderInfo {
    ...
    pub burn_header_height: u32,
    ...
}
```

Per Jude
> we are constrained by the block-commit wire format to use 32 bits for block height, but the vast majority of the codebase uses 64 bits for a block height. the reason for this is that the block-commit wire format is specific to Bitcoin, and we only have 80 bytes to work with.  If we ported the system to, e.g., Stacks itself, then we could comfortably support 64-bit block heights
I'm in favor of making the whole system 64-bit, except for the block-commit wire format (since we're not married to Bitcoin)

**Comment by jcnelson** [comment]
There's an engineering difficulty: the MARF uses 32-bit block heights.  This needs more investigation on how invasive of a change it would be to convert the MARF to using 64-bit block heights.
