### ISSUE TITLE
PoX: Update user burn operation to require paying to PoX recipients

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#2028]
The UserBurnSupport operation currently requires that _all_ commitments be burn commitments: even when the corresponding LeaderBlockCommitOp would need to use PoX reward addresses.

I think this should be updated such that user burn supports must pay to PoX reward addresses. Failing to do this would reduce PoX rewards in the presence of lots of user burn support (though we do not expect there to be much incentive for participants to use user burn supports), and also potentially allow miners who wished to ignore PoX to channel most of their BTC commitments through user burn supports (though they would be shouldering an additional cost to do so).

**Comment by jcnelson** [comment]
Update: let's disable this until Stacks 2.1
