### ISSUE TITLE
Genesis and Net Tests Flakiness

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-blockchain#2207]
**Describe the bug**

There are some general inconsistent failures with Genesis and Net tests in the `stacks-blockchain` Github workflow.

[See here for an example workflow run of inconsistent failures.](https://github.com/blockstack/stacks-blockchain/actions/runs/438281299)

Examples of failed Genesis or Net tests include:
* `pox_integration_test`
    ```
    #12 625.1 thread '<unnamed>' panicked at 'error binding to 127.0.0.1:50303: error creating server listener: Address 
    already in use (os error 98)', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.3/src/server.rs:211:27
    ```
* `size_check_integration_test `
    ```
    [ThreadId(380)] Failed to mine one microblock: ChainstateError("Stacks chainstate error: NoTransactionsToMine")
    #12 1531. WARN [1608652315.651479] [src/chainstate/stacks/miner.rs:299] [ThreadId(411)] Error processing TX 
    738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c: Bad nonce: origin account 
    ST3WM51TCWMJYGZS1QFMC28DH5YP86782YGR113C1 nonce of tx 
    738e4d44636023efa08374033428e44eca490582bd39a6e61f3b6cf749b4214c is 0 (expected 5)
    ```
* `test_2_nat_miners.sh`
    ```
    #16 602.2 Master node failed to boot uptest_2_nat_miners.sh exit 1
    #16 602.2 mv bitcoin-1608650846 archive/1608651448
    #16 602.2 mv bitcoin-neon-controller.log archive/1608651448
    #16 602.2 mv bitcoin.log archive/1608651448
    #16 602.2 mv chainstate-master-test-2-nat-miners archive/1608651448
    #16 602.2 mv faucet.log archive/1608651448
    #16 602.2 mv log-master-test-2-nat-miners.log archive/1608651448
    #16 602.2 Running test_2_nat_miners_1_follower.sh
    #16 602.2 [464] Setting up bitcoind...
    #16 602.2 [464]  Generating bitcoind config file...ok
    #16 602.2 [464] Starting bitcoind...PID 478
    #16 607.2 [464] Setting up bitcoind controller...
    #16 607.2 [464]  Generating bitcoind controller config file...ok
    #16 607.2 [464] Starting bitcoind controller...PID 489
    #16 612.2 [464] Setting up bitcoin faucet...
    #16 612.2 [464]  Importing faucet private key...FAILED!
    ```
**Steps To Reproduce**
Run the `stacks-blockchain` workflow against any branch. Some runs may contain the errors shown above, but they may not always occur.

**Expected behavior**
Tests should either consistently fail due to non-environmental issues (hinting at an actual bug), or consistently pass.

**Environment (please complete the following information):**
 - OS: Debian (buster)
 - Rust version: The version is not locked, `rust:buster` is often used in the Docker images running these tests.
 - Version of the appropriate binary / software package: `v24.2.1.0-xenon`

**Comment by kantai** [comment]
It looks like the genesis test flakiness is improved by (https://github.com/blockstack/stacks-blockchain/pull/2213/commits/40908325be9449afe95b93fbe50b9153f93e1164) -- it doesn't remove all the flakiness, I think, because this change really just masks a potential underlying test issue. Basically, the variable that the test uses to detect when the test node has processed the next block may miss a block, which could either mean that the node stalled, or that the test variable just missed the change. If the flakiness is happening because of the former reason, this will still lead to test failures. However, I suspect that it's the second reason.

**Comment by kantai** [comment]
This remains an issue, though it's morphed a little bit. We still have flakiness in our integration tests, but recent PRs like #2715 addressed _some_ of the flakiness.
