### ISSUE TITLE
Refactor: Decouple Clarity VM

### ISSUE THREAD

**Issue by reedrosenbluth** [stacks-network/stacks-blockchain#2398]
The Clarity `VM` is tightly coupled with the rest of the codebase. This has many implications, including that projects like the Clarity REPL can't depend on the Clarity `VM` alone. I'd like to decouple the `VM` to the point that it can be published as its own crate.

Remaining work:
- [ ] remove remaining `blockstack_lib` dependencies [M]
    - [ ] from `util`
    - [ ] from `vm`
- [ ] expose `vm` as its own crate [M]

**Comment by jcnelson** [comment]
From meeting -- Start with removing dependencies on the `util` module.

**Comment by reedrosenbluth** [comment]
One of the big remaining pieces of this task is exposing `vm` as a separate library. Two possible approaches are:

1. Keep `vm` as a part of `blockstack_lib` while simultaneously exposing it as its own library
    a. I've had trouble getting this to work... am not confident it is possible without some hacky scripting
2. Hoist `vm` up to the top level, add it as a workspace member, and make `blockstack_lib` depend on it
    a. This would also involve hoisting up `types` and `util`, since there can't be a circular dependency on `vm` and `blockstack_lib`
    b. This is definitely more work than the first approach, and would be a more invasive change.

@kantai @lgalabru @jcnelson @pavitthrap thoughts on the best way to move forward with this?

**Comment by kantai** [comment]
It _should_ be possible to implement (1) in a not-too-hacky fashion.

I pushed a branch `feat/libvm` that implements (1) by:

Adding a new `libvm` workspace member, with a new Cargo.toml file with just a `[lib]` output. This TOML file just references:

```
[lib]
name = "libvm"
path = "../src/libvm.rs"
```

And `libvm.rs` for now is just a wholesale clone of `lib.rs`, but we could selectively pair down the includes in that file to help with Clarinet's build.

**Comment by reedrosenbluth** [comment]
@kantai amazing!

Will work with @lgalabru on getting Clarinet to use `libvm`.

**Comment by jcnelson** [comment]
This done now?

**Comment by kantai** [comment]
Yep
