### ISSUE TITLE
Stacks 2.1 migration logic

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2464]
We need a standard way for activating new features at the Stacks 2.1 block height.  Review on consensus-critical and stacks-2.1 PRs is blocked on us knowing how the migration logic is going to work.

**Comment by psq** [comment]
the mechanism is one thing, but what is the process to decide which features do get added, and which don't?  Probably should involve a number of different constituents (community, stx holders, miners, foundation...  random order, just throwing ideas in here)

**Comment by jcnelson** [comment]
That would be handled via the SIP process.

**Comment by jcnelson** [comment]
I think we're pretty much good on this, with `StacksEpoch` and `ClarityVersion`.  There's some cleanup we can do on these gates, but that's better captured in a refactoring issue and can wait until after 2.1 launches if need bel.
