### ISSUE TITLE
[networking] report node version in-band, in order to measure out software release roll-out

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2467]
There's a few ways to do this:

* The node version could be reported within the p2p interface messages, so inbound (NAT'ed) peers report their version numbers to publicly-routable peers (and thus render this information discoverable)
* Miners could write their node's version number to the coinbase scratch area by default
* Miners could write a version counter to the `memo` field of a block-commit by default

The purpose of this is to determine how much of the network's mining power has rolled out a bugfix, so the Hiro and the Foundation can know when it is safe to publicly disclose a vulnerability.  Nodes and miners are of course free to report whatever they want, but they are incentivized to be honest so that a vulnerability disclosure doesn't put them at risk.

**Comment by diwakergupta** [comment]
I think we still want this.

**Comment by diwakergupta** [comment]
@jcnelson I know we've been able to do some tracking of rollout in the last two releases. Is that method generic -- if so, should we close this?
