### ISSUE TITLE
[mining] possible failure to propagate a mined block if the subsequent block is a flashblock

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2495]
I'm currently investigating a rare but interesting phenomenon that could be leading a miner to produce an unviable fork.  Recently (last 7 days), a miner managed to produce a fork of several blocks that no other nodes could process, because they were all missing its ancestor.  Details below:

* This forking phenomenon has only happened twice, and they were both in the last week.
* The two missing ancestors were mined by the same miner (SPP1D), in Bitcoin transactions `7affdd4cb9c264afc750c4317266f4ca8711b7345623255979c5ca1ea5a58c73` and `34caf7b970880fcbaa67babbf8737f89ba475f481792e2e376a9c75e6ce084b5`
* In both cases, the miner won this sortition and the subsequent sortiton.
* The subsequent sortition was in a flash block.

Even though there's just two data points here, this is enough for me to be suspicious that there's something amiss in how a miner propagates a block if a flashblock arrives right afterwards.

**Comment by kantai** [comment]
Diving into this issue -- it's difficult to figure out without logs from the node that produced the block.

The code path that the miner would take here wouldn't be impacted by a flash block situation: if the miner ever applied the block to its chainstate, it would attempt to broadcast it, but it may have failed to initially broadcast for one of two reasons:

1. The broadcast recipients' network endpoints were busy (this occurred near a down time for the seeds)
2. The node's chains coordinator thread didn't process the state within 15 seconds (which is unlikely, the block, once broadcasted, processed in around 200 ms).

Eventually, the block was distributed to the network, probably via the anti-entropy protocol, but it took 5 hours. The nodes that had the block data did not have their RPC ports publicly available. Bumping the anti-entropy protocol from daily to hourly would improve this situation slightly.

The other thing I'll investigate is whether (2) may have been exacerbated by the flash block: if the chains coordinator was busy processing a sortition, its conceivable that it took longer than the processing timeout. This logic in the miner could probably be improved -- the miner could instead broadcast their block in all cases, and then try to apply the block themselves.
