### ISSUE TITLE
TOML config parsing improvements

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-blockchain#2511]
**Describe the bug**
Currently if `stacks-node` has a problem parsing properties in a given config `toml` file, it will immediately abort due to a panic and dump a stacktrace. The error doesn't direct the user that the problem exists in the config file, nor does the stack trace. This can lead to confusion and generally make the user experience more difficult when trying to understand the problem.

In addition, numerical properties like `rpc_port` and `peer_port` will cause the process to abort if their values have quotes around them. For example:
```
rpc_port = "8332"
```

The config TOML parsing logic should ideally _not_ abort in this scenario and instead attempt to convert the value to an integer and continue. 

**Steps To Reproduce**
Create a `config.toml` file containing the following contents:
```
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd48836408d9cf437344b63516@seed-1.mainnet.stacks.co:20444,03652212ea76be0ed4cd83a25c06e57819993029a7b9999f7d63c36340b34a4e62@seed-2.mainnet.stacks.co:20444"

[burnchain]
chain = "bitcoin"
mode = "mainnet"
peer_host = "bitcoin2.blockstack.com"
rpc_port = 8332
peer_port = 8333
```

And run it via `stacks-node start --config config.toml`.
The process will abort but not direct the user to the reason of the problem (peer_host address goes nowhere):

```
root@7813346a5edf:/stacks# stacks-node start --config config.toml
INFO [1615585131.083300] [testnet/stacks-node/src/main.rs:80] [main] stacks-node 0.1.0 (HEAD:e7f178bdb+, debug build, linux [x86_64])
INFO [1615585131.084597] [testnet/stacks-node/src/main.rs:125] [main] Loading config at path config.toml
Process abort due to thread panic
   0: stacks_node::main::{{closure}}
             at /tmp/build/80754af9/stacks-blockchain/testnet/stacks-node/src/main.rs:57
...
```

**Expected behavior**

1. Numerical properties like `rpc_port`, `peer_port`, and any others that may exist should attempt to convert the value from a string to an integer if a string is provided.
2. Otherwise the process aborts, printing an informative error that either points out the problematic property, or the line number of the suspected problem.

**Comment by lgalabru** [comment]
Related: https://github.com/blockstack/stacks-blockchain/issues/1945/

**Comment by jcnelson** [comment]
Let's see if the TOML processing crate can print out the particular error, given a schema.

**Comment by jcnelson** [comment]
Also, see if we can use a TOML crate that is aware of the environment variables, and lets us template them.

**Comment by CharlieC3** [comment]
Additionally, the default `working_dir` will always have `stacks-testnet` in its name, even if it's a mainnet node. This should be pretty easy to address as part of this issue, but I can file it in a new ticket if it's best to organize it that way.
https://github.com/blockstack/stacks-blockchain/blob/master/testnet/stacks-node/src/config.rs#L1057

**Comment by lgalabru** [comment]
I think this is no longer the case in the `develop` branch - it's now `stacks-node-{timestamp}`

**Comment by igorsyl** [comment]
Fix merged to develop branch: https://github.com/stacks-network/stacks-blockchain/pull/3168
