### ISSUE TITLE
PoX Updates: `stack-increase`

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#2533]
As part of updating PoX in Stacks 2.1, the PoX contract should implement:

```
;; increase the amount in "tx-sender"s active lockup
(define-public (stack-increase (increase-by uint)))
;; increase the amount in a delegated active lockup
(define-public (delegate-stack-increase (stacker principal) (increase-by uint)))
```

to enable increasing the amount that a particular stacker has locked.

**Comment by jcnelson** [comment]
The interface should be as follows:

```clarity
;; increase the amount in "tx-sender"s active lockup
(define-public (stack-increase (increase-by uint) (index uint)))
;; increase the amount in a delegated active lockup
(define-public (delegate-stack-increase (stacker principal) (increase-by uint) (index uint)))
```

The `index` indexes the `reward-cycle-pox-address-list` map.

**Comment by saralab** [comment]
@jcnelson : @kantai  can help with along with https://github.com/stacks-network/stacks-blockchain/issues/2534 , Let me know if I can mark him as the assignee here .

**Comment by saralab** [comment]
Can we close this issue? The PR was merged .

**Comment by jcnelson** [comment]
Yes
