### ISSUE TITLE
PoX: native segwit support

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2586]
Add support for native segwit address payouts.  Two items of complexity:

* Using `wtxid` pervasively throughout the codebase
* Upgrading the miner to create segwit outputs and possibly consume segwit inputs

**Comment by raymonddurk** [comment]
I'd love to update this proposal one step further to include bech32m addresses (Taproot). While I also agree native segwit support of bech32 should be supported as it is harder and harder to find non-segwit wallets, it would have further impact than an increase in user experience.

1. The savings on Bitcoin fees would increase the decentralization as it has a direct relationship with the minimum number of Stacks needed for stacking to be above the dust limit and or run profitably. 
2. It is an irresponsible use of chain space which would increase the bitcoin fee market and be a centralising force as the inverse of the first point.
3. If anyone is paying out from a multisig, Schnorr would provide more of the rewards payouts to stackers
4. Moving to Taproot could open the door for new engineering opportunities to take advantage of things being built with those three new BIPs and the subsequent development that comes in the next few years.

**Comment by zone117x** [comment]
Do we expect function signatures for PoX-2 to change from the ones in PoX-1 (e.g. `stack-stx`, `delegate-stack-stx`, etc) in order to support segwit? Or is it more likely we'll end up with new functions like `stack-stx-segwit`?

**Comment by jcnelson** [comment]
The new type signature for a PoX address will be `{ (hashbytes (buff 32)) (version (buff 1)) }`.  New `version` values will be added to represent p2wpkh, p2wsh, and p2tr, and the `hashbytes` field will be checked at runtime to ensure that it is either 20 bytes or 32 bytes depending on `version`.

**Comment by janniks** [comment]
Does a stacks-node need to know about the [**witness** version](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#segwit-address-format) of a bech32 native segwit address pox-address when converting the address to a scriptPubkey? — i.e. _`OP_n` (`OP_0` through `OP_16`)_ etc.

**Comment by jcnelson** [comment]
This is now merged!
