### ISSUE TITLE
Send additional data to event observer for Stacks-over-BTC wire formats

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#2591]
See issue https://github.com/blockstack/stacks-blockchain-api/issues/415

> this address should be the first output address of the bitcoin transaction. I realize that the `stacks-node` doesn't currently provide enough information to obtain this, so changes would be required there as well, but we should discuss in a new issue.

_Originally posted by @kantai in https://github.com/blockstack/stacks-blockchain-api/pull/414#r564097195_

The API is unable to generate accurate data for stx-stack operations performed via btc txs.

**Comment by zone117x** [comment]
Not stale AFAIK. @kantai any modern context here?

**Comment by kantai** [comment]
No more modern context here. Is the API currently able to get this data for the `stx-transfer` BTC operations? Or is this issue for providing data on both `stack-stx` and `stx-transfer` BTC ops?

**Comment by jcnelson** [comment]
This now happens in 2.1.
