### ISSUE TITLE
Add bitwise AND, OR and NOT functions to Clarity.

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#2595]
**Is your feature request related to a problem? Please describe.**
I would like to implement in clarity simple RBAC mechanism using bitmasking. To do it correctly I need to have access to bitwise AND, OR and NOT operations.
Currently only `XOR` is available and it not a universal operation therefore other operations can't be build with it.

**Describe the solution you'd like**

AND
**Signature:** `(and i1 i2)`
**Input:** `int, int | uint, uint`
**Output:** `int | uint`

OR
**Signature:** `(or i1 i2)`
**Input:** `int, int | uint, uint`
**Output:** `int | uint`

NOT
**Signature:** `(not i1)`
**Input:** `int | uint`
**Output:** `int | uint`

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jcnelson** [comment]
Hi @LNow, nothing stops you from multiplying or dividing by powers of 2 in order to test and set bits.

**Comment by LNow** [comment]
Hi @jcnelson, setting value of single bit is simple if I know its value prior change. My main problem is with testing.


| Role | Decimal | Binary|
|--------|------------|----------|
| A | 1 | 000001 |
| B | 2 | 000010 |
| C | 4 | 000100 |
| D | 8 | 001000 |
| E | 16 | 010000 |
| F | 32 | 100000 |

Setting role can be done by addition of decimal values if I know that it has not been set previously.
Removing role can be done by subtraction of decimal values if I know that it has been set previously.

What about testing?

How to test if someone have one selected role (value of single bit)?
> Jane have roles B and C (000110). How to verify if she have role A, B or C one by one?


How to test if someone have one or more roles (value of multiple bits)?
> To perform action XYZ you need to have one of following roles: A, C, E, F (110101).
> Jane have roles B and C (000110).
> How to test if she is allowed to perform XYZ?

**Comment by jcnelson** [comment]
Here you go

```
;; Determine if the ith bit in a uint is set to 1
(define-read-only (is-bit-set (val uint) (bit uint))
    (is-eq (mod (/ val (pow u2 bit)) u2) u1)
)

;; unit test
;; check bits in 0b10011100 (u156)
(begin
    (asserts! (not (is-bit-set u156 u0)) (err u0))
    (asserts! (not (is-bit-set u156 u1)) (err u1))
    (asserts! (is-bit-set u156 u2) (err u2))
    (asserts! (is-bit-set u156 u3) (err u3))
    (asserts! (is-bit-set u156 u4) (err u4))
    (asserts! (not (is-bit-set u156 u5)) (err u5))
    (asserts! (not (is-bit-set u156 u6)) (err u6))
    (asserts! (is-bit-set u156 u7) (err u7))
    (ok true)
)
```

**Comment by lgalabru** [comment]
Duplicate - https://github.com/blockstack/stacks-blockchain/issues/1150.
What's our take on `not`, `and` and `or` also admitting buffs in Clarity 2.1 ?

**Comment by jcnelson** [comment]
AFAIK other programming languages only define bitwise operators on integer types, so they shouldn't apply to buffers.  However, I firmly believe that we should have fast, cheap built-ins to (1) take byte-slices of buffers, and (2) convert `(buff u16)` to `uint` / `int` and back. From there, you can implement bitwise operators on buffers via `fold`.

**Comment by LNow** [comment]
Thanks @jcnelson. 

With regards to multi-bit check:
```
;; `xor` flips bits if they don't match, so if there are no matching bits it will perform mathematical addition.

(define-read-only (have-common-bits (valueA uint) (valueB uint))
  (not (is-eq (xor valueA valueB) (+ valueA valueB)))
)
```
