### ISSUE TITLE
Mocknet pox endpoint not working

### ISSUE THREAD

**Issue by kyranjamie** [stacks-network/stacks-blockchain#2600]
## Describe the bug

`/v2/pox` endpoint not working when running in mocknet.

## Steps To Reproduce

Booting mocknet on develop 7ba919a52, running

`cargo run --release --bin=stacks-node --package=stacks-node --  mocknet`

Waited for it to start producing coinbase blocks.

`curl "http://127.0.0.1:20443/v2/pox"` Responds with 500 error

```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: origin, content-type
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Origin: *
Content-Length: 25
Content-Type: text/plain
Date: Wed, Apr 21 2021 11:55:56 GMT
Server: stacks/2.0
X-Request-Id: 2564431540

Failed to query peer info
```

cc/ @zone117x

**Comment by jcnelson** [comment]
You need to wait for it to mine a few blocks -- namely, at least as many as the number of confirmations required for there to be a "stable" block height (in production, this is 6 blocks).

**Comment by zone117x** [comment]
This is a regression in mocknet mode, it didn't used to have this behavior. It also never seems to resolve even after waiting for 200 block confirmations. This breaks a lot of integration tests in the API.

**Comment by kyranjamie** [comment]
Yeah indeed. Impact for UserX team is that is prevents use from being able to test stacking in our client apps.

**Comment by diwakergupta** [comment]
@lgalabru can you take a look? If it's an easy fix, maybe you can point @pavitthrap in the right direction?

**Comment by lgalabru** [comment]
@pavitthrap when spawning a mocknet node (`cargo run --release mocknet` from `testnet/stacks-node`) and hitting `GET /v2/pox`, you'll see that this calling is failing with the logs

```
Apr 22 14:42:00.113007 INFO Handle GET /v2/pox
Apr 22 14:42:00.201810 ERRO PoX Constants in config mismatched with PoX contract constants: 30 != 1
Apr 22 14:42:00.201828 WARN Failed to get PoX info GetPoxInfo(HttpRequestMetadata { version: Http11, peer: PeerHost::DNS(localhost,20443), keep_alive: true }, None): DBError(Corruption)
```

It looks like we recently introduced some additional checks in the rpc handler catching an issue on mocknet - mocknet nodes end up being loaded with the `regtest` PoxConstants. It should probably use the `testnet` pox constants instead.
