### ISSUE TITLE
Epoch switch: instantiate the PoX 2.1 contract and extension contracts at the epoch boundary

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2611]
When the Stacks 2.1 epoch switch happens, the version of the PoX contract will need to be instantiated, as well as any extension contracts.

**Comment by kantai** [comment]
I'm currently working on the process of PoX 2.1 contract instantiation. The extension contracts are somewhat similar, but probably sufficiently different that they'll need their own issue as well.
