### ISSUE TITLE
Implement static cost database 

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#2671]
Options 
- MARF metadata 
- indexed SQLite tables (similar to sortition/ block header data 
   - use Stacks block id to guarantee uniqueness

**Comment by jcnelson** [comment]
Static cost analysis data is not consensus-critical, so it would probably belong in the same DB as the clarity metadata (possibly even in the same table), indexed by the Stacks block id.

**Comment by pavitthrap** [comment]
@jcnelson Are you referring to the AnalysisDatabase?
