### ISSUE TITLE
Clarity `filter` function should have an additional parameter for filter conditions

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#2679]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to have a possibility to control filter conditions applied in input function used in `filter`function. That way I won't have to write multiple filter function which differ only in that one filters out values less than 5, another less than 6, another 7, 8, 9 etc.

**Describe the solution you'd like**
Filter function should have an additional parameter that we could use to pass filter condition.

Signature: `(filter func list filer-condition-data)`

Thanks to that we could write contracts like this:
```clojure
(define-data-var data (list 10 uint) (list u1 u2 u3 u4 u5 u6 u7 u8 u9 u10))

(define-read-only (get-lower-than (value uint))
  (filter get-lower-than-closure (var-get data) value)
)

(define-private (get-lower-than-closure (element uint) (limit-value uint))
  (< element limit-value)
)
```

**Describe alternatives you've considered**
Right now dynamic filtering can be achieved by saving filter conditions in variables and reading their values in `filter` function, but this approach works only for public functions and is not very efficient as we have to read same variable values over and over again.

```clojure
(define-data-var data (list 10 uint) (list u1 u2 u3 u4 u5 u6 u7 u8 u9 u10))

(define-public (get-lower-than (value uint))
  (begin
    (var-set limit-value value)
    (ok (filter get-lower-than-closure (var-get data)))
  )  
)

(define-data-var limit-value uint u0)
(define-private (get-lower-than-closure (element uint))
  (< element (var-get limit-value))
)
```

**Comment by friedger** [comment]
What about 
```clojure
(define-data-var data (list 10 uint) (list u1 u2 u3 u4 u5 u6 u7 u8 u9 u10))

(define-read-only (get-lower-than (value uint))  
  (fold get-lower-than-closure (var-get data)  {limit-value: value, result: (list)}))
 
(define-private (get-lower-than-closure (element uint) (ctx {limit-value: uint, result: (list 10 uint)}))  
  (if (< element (get limit-value ctx))    
    {limit-value: (get limit-value ctx), 
     result: (unwrap-panic (as-max-len? (append (get result ctx) element) u10))}
    ctx))

```

see [clarity tools](https://clarity.tools/code?KGRlZmluZS1kYXRhLXZhciBkYXRhIChsaXN0IDEwIHVpbnQpIChsaXN0IHUxIHUyIHUzIHU0IHU1IHU2IHU3IHU4IHU5IHUxMCkpCiAKKGRlZmluZS1yZWFkLW9ubHkgKGdldC1sb3dlci10aGFuICh2YWx1ZSB1aW50KSkgIAogIChmb2xkIGdldC1sb3dlci10aGFuLWNsb3N1cmUgKHZhci1nZXQgZGF0YSkgIHtsaW1pdC12YWx1ZTogdmFsdWUsIHJlc3VsdDogKGxpc3QpfSkpCiAKKGRlZmluZS1wcml2YXRlIChnZXQtbG93ZXItdGhhbi1jbG9zdXJlIChlbGVtZW50IHVpbnQpIChjdHgge2xpbWl0LXZhbHVlOiB1aW50LCByZXN1bHQ6IChsaXN0IDEwIHVpbnQpfSkpICAKICAoaWYgKDwgZWxlbWVudCAoZ2V0IGxpbWl0LXZhbHVlIGN0eCkpICAgIAogICAge2xpbWl0LXZhbHVlOiAoZ2V0IGxpbWl0LXZhbHVlIGN0eCksIAogICAgIHJlc3VsdDogKHVud3JhcC1wYW5pYyAoYXMtbWF4LWxlbj8gKGFwcGVuZCAoZ2V0IHJlc3VsdCBjdHgpIGVsZW1lbnQpIHUxMCkpfQogICAgY3R4KSkKCihnZXQtbG93ZXItdGhhbiB1NCk=)

**Comment by LNow** [comment]
Yes, that's another way to tackle it.
For read only function - works perfectly fine as long as list is not very long. We use similar approach in CityCoin.

**Comment by LNow** [comment]
@kantai would it be possible to add this to Clarity v2 scope?

**Comment by MarvinJanssen** [comment]
All iterator functions could use something like this. Try passing in a trait ref for example...

**Comment by kantai** [comment]
Would be happy to review a PR opened against `next` (the branch for 2.1 changes) that implements this.

The thing to be careful of is that the iterator functions currently do allow applying the iterator over multiple _list_ arguments, and this would need to differentiate between arguments supplied as "lists" versus the atomic elements of the iteration.

**Comment by njordhov** [comment]
The `filter` function could be variadic, taking multiple lists as argument like`map`, while returning values from the first. This could be used with the suggested `repeat` function: https://github.com/clarity-lang/reference/issues/52 for passing in additional arguments.
