### ISSUE TITLE
PoX 2.1: Bitcoin scripts instead of addresses 

### ISSUE THREAD

**Issue by lgalabru** [stacks-network/stacks-blockchain#2695]
What's our take on giving the ability to stackers to pass a bitcoin script, instead of addresses when stacking?
Intuition tells me that it would open some new doors in terms of protocol design.
The "only" downside that I'm seeing would be that certain block commits could be more expensive than others, which is something that could be constrained maybe?

**Comment by jcnelson** [comment]
I'm against arbitrary scripts. It opens a DoS attack on mining, because a Stacker could insert an invalid scriptPubKey and thereby prevent anyone from mining when its reward slot is up for payment.  It could even happen by accident, in the absence of malice.
