### ISSUE TITLE
List of reserved words in clarity

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#2696]
I started working on [ANTLR4 grammar files](https://github.com/LNow/clarity-antlr4) for Clarity and although they are almost complete I struggle with figuring out which words in clarity are reserved and which are not.

At the beginning I thought all keywords, datatype names and function names are reserved, but I couldn't be more wrong.
Is there any specific place in the stacks-node code where I should look for such words?

Due to code examples posted below (100% valid and executable) I don't know if Clarity have no, or very few, reserved words.
```
(define-map TestMap
  {uint: uint}
  {
    len: uint,
    define-public: principal,
    principal: bool,
    bool: (string-ascii 80)
  }
)

(map-set TestMap
  { uint: u1 }
  {
    len: u0,
    define-public: 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE,
    principal: false,
    bool: "hello"
  }
)

(define-read-only (define-public)
  "hello"
)
```
```
(define-private (principal)
  "hello world"
)

(define-read-only (uint (bool (string-ascii 30)))
  bool
)

(define-public (define-read-only)
  (ok (uint (principal)))
)
```
```
(define-map Principals principal {principal: {principal: {principal: principal}}})

(define-public (set-principal (Principal principal))
  (ok 
    (map-set Principals Principal { principal: {principal: {principal: Principal}}})
  )
)
```

**Comment by LNow** [comment]
Let me different question.
What criteria do you use when determining what should be treated as a keyword and what should not and in what context?

**Comment by njordhov** [comment]
@LNow A Clarity parser doesn't need reserved keywords nor productions for every native function but can cover these with a common rule for symbols, thanks to the simple S-expression syntax.  Here is a complete parser for Clarity in less than 50 rules: https://github.com/njordhov/clarity-parser/tree/main/src

**Comment by LNow** [comment]
@njordhov Sure, we can make parser without reserved keywords. We can make Clarity 100% lisp like, and allow users to define and redefine whenever, wherever and whatever they want with all consequences it implies.
But we already have reserved keywords. That is why I think all keywords should be reserved.

We should either move all the way in one or another direction. Anything in between will lead to confusion - which is exactly what we are dealing with right now.
