### ISSUE TITLE
Add ability to change reward address for next cycle

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-blockchain#2705]
In Stacks 2.1, it would be great if it was possible to change the BTC reward address while in the middle of Stacking. Beyond the most obvious uses for this (i.e. change in custody), this would support many interesting abstractions around Stacking. For example, Stackers could receive a fixed up-front payment in exchange for letting someone else take the Stacking rewards. There are also many interesting applications around pools that could use this.

This example is possible today, but it would require fully un-stacking and then missing a cycle. With this feature, a Stacker could lock for many cycles and allow their slots to be "rented" individually.

**Comment by jcnelson** [comment]
Hey @hstove, we'll need to think a bit more about this.  It's possible that this would be infeasible, given the structure of the contract, but we'll see.

**Comment by jcnelson** [comment]
So, we can do this -- you'd just use `stack-extend` and stack for only one reward cycle.  This is already implemented in `next`.
