### ISSUE TITLE
Miner accidentally commits same BTC twice

### ISSUE THREAD

**Issue by vysegrad** [stacks-network/stacks-blockchain#2706]
Setup:

Raspberry Pi 4
Latest Stacks miner

Miner has committed same btc amount (570000 sats) twice on the exact same timestamp. Seems like identical btc commit has been added to one block instead of the usual 10 minutes apart.

Transaction id's:

df37a2d4b3243314c8f40e5534dcadefe744e290b1ad1151869ef4e37a69c9c8

c9ca4471ceb1960a0e2130cda05f60265b3833edc53e95af38e7a911f8b6cca1

84094f80f85f964f9bb07e72b55e6d67ccf69a5c40a532b0a51a6a3cf9639bbd, payload: Coinbase, origin: SPVAA2R97W9NNZ4E3SYFCVTFG6GA3P9H6SAMV748

@jcnelson thoughts?

**Comment by jcnelson** [comment]
Not sure, but I definitely see it happening.  It seems the miner is spending two different UTXOs in the same block.  Did you refill your address at that time?

**Comment by vysegrad** [comment]
> Okay, I dissected the OP_RETURNs in both of those transactions. They're definitely block-commits for different Stacks blocks, and the miner sent them with different burn block modulii. Specifically, df37a...9c9c8 has burn modulus 4 (i.e. it was sent when the Bitcoin tip height mod 5 was 4), and c9ca4...6cca1 burn modulus 3 (i.e. it was sent when the Bitcoin tip height mod 5 was 3). Both transactions landed in Bitcoin block 687185. The most likely interpretation of these events is that c9ca4...6cca1 was late, since it was sent when the Bitcoin block chain tip height was likely 687183. The block-commit in df37a...9c9c8 was likely generated when the Bitcoin chain tip was 687184, which would mean it was on-time.

@jcnelson thanks for taking the time on this issue. I recall that i was consolidating my UTXOs in Electrum wallet with a low fee when starting mining. Could this have caused the issue as the low-fee consolidation transaction was still being confirmed when the miner started running?

**Comment by jcnelson** [comment]
That's possible, but it's hard to say that it was the cause.  In general, Bitcoin miners aren't required to mine block-commit transactions in the blocks you target them for, which means your transaction can get pushed back by a block or two just by accident.

**Comment by MaksimalistT** [comment]
@jcnelson  take a look at this weird stacks and btc block sequence
<img width="746" alt="Screen Shot 2021-06-17 at 6 21 32 PM copy" src="https://user-images.githubusercontent.com/77570471/122606149-241a6400-d081-11eb-9599-2d6a94a2c4b4.png">

**Comment by jcnelson** [comment]
This might also have been caused by the node processing stale `ProcessTenure` requests, which is fixed in 2.05.0.1.0-rc4.  Going to go ahead and close this issue for now; please re-open if it happens again.
