### ISSUE TITLE
feat(costs): Benchmark costs for Clarity2 functions

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#2800]
This is a feature request for *benchmarking* of Clarity2 functions.

We already have Issue #1165 for benchmarking Clarity functions.

However, what might lost in the shuffle is the fact that we also need to benchmark the *new* functions being added for Clarity2, to be released at the same time as the first benchmarked cost functions.

The new functions can be found in the branch `next` at:
https://github.com/blockstack/stacks-blockchain/blob/next/src/vm/functions/mod.rs#L56

These functions will be annotated as `ClarityVersion::Clarity2`.

**Comment by diwakergupta** [comment]
@pavitthrap this can be closed right?

**Comment by jcnelson** [comment]
This is done.
