### ISSUE TITLE
Implement "Queryable Logging" for Transactions

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#2815]
We should have two changes to the codebase:

1) All outcomes for transactions should be logged, whether "success", "error", or "skipped". It should not be possible for a transaction to be considered/processed and then nothing get logged about the outcome.

2) This logging should be done in "queryable form", so that a fixed query can be issued to the logs for a given transaction, in order to find out the outcome.

**Comment by jcnelson** [comment]
Isn't this essentially the `txindex` feature?

**Comment by gregorycoppola** [comment]
@jcnelson I didn't know about this feature. I like the idea of logging to a database instead of/in addition to writing to the sequential logs. But, what info does this feature give if there is an error? I'll try it out!

**Comment by kantai** [comment]
> Isn't this essentially the STACKS_TRANSACTION_LOG feature?

It's a little different -- the log messages would provide a log of every time a particular tx is _considered_, whereas the DB just tracks current tx status.

**Comment by gregorycoppola** [comment]
I believe there are indeed some gaps in what is logged by `STACKS_TRANSACTION_LOG`. But, these holes could be plugged with a little work.

At this point I think there are two options for accomplishing the goal of this issue.

1) The first option is to follow the `STACKS_TRANSACTION_LOG` approach suggested by @jcnelson , which is to *capture the outcomes of all events*, e.g., in a vector, and then have a **SINGLE** place at the end of processing where we iterate through all the log events from the batch, and do the logging. The work item would be to expand the existing interfaces to make sure we can capture all cases, and to otherwise make sure the feature is tested.

2) The second option, which is what I did in #2812, is to have **many** log points, where, anytime we feel like a log is needed, we just add more log statements to the code. This saves the work of adapting the interfaces to always propagate information. The downside is that it does not result in a coherent system. It's more like "whack-a-mole".

I prefer the first option, because it is more foolproof. With the "many log points" approach, there is no clear pattern, and always the worry that some log points will be missed, either initially or in the future. With "one log point" approach, the compiler will effectively force us to never forget to create a log for an event, because the propagation of events is checked by the function return types.

The first option is more work, and with #2812 we were trying to find an active bug, so I didn't bother with the refactor.

But since the `STACKS_TRANSACTION_LOG` feature already exists, I think it makes sense to just do the work expand upon this "capture events and log once" approach, which is the most foolproof for the long run.

**Comment by kantai** [comment]
> I prefer the first option, because it is more foolproof. With the "many log points" approach, there is no clear pattern, and always the worry that some log points will be missed, either initially or in the future. With "one log point" approach, the compiler will effectively force us to never forget to create a log for an event, because the propagation of events is checked by the function return types.

I think _both_ options have this problem -- with the TRANSACTION_LOG, the code that would emit a log event in the second option would instead need to update the transaction log. Either way a "missed event" is possible. Probably _both_ options should be implemented: logging statements are useful even with the existence of a transaction log, because they would record state change history. The transaction log is primarily useful for quickly querying the current status of a transaction.

**Comment by gregorycoppola** [comment]
I guess one drawback of "collect all events and log later" would be if there is a "panic" before the events can be logged.

However, the problem is never really panicking in practice.

**Comment by gregorycoppola** [comment]
If we don't log at the point in time, then the chronological logs won't make sense.

Maybe we can do the "both" approach. I like the idea of forcing the interfaces to propagate these events, because I think it will clarify them.

**Comment by kantai** [comment]
> Maybe we can do the "both" approach. I like the idea of forcing the interfaces to propagate these events, because I think it will clarify them.

Yes -- one option for forcing the interface to surface transaction results is refactoring the loop in the anonymous function supplied to `iterate_candidates`  (~line 1409 of `miner.rs`) such that it looks like:


```rust
        let result = mempool.iterate_candidates(tip_height, |available_txs| {
            if block_limit_hit == BlockLimitFunction::LIMIT_REACHED {
                return Ok(());
            }

            for txinfo in available_txs.into_iter() {
                let result = consider_tx(txinfo, ...);
                debug!("Considered transaction"; "txid" => %txinfo.txid, ... );
                match result {
                   // update necessary tracking data (block_limit_hit, mined_origin_nonces, etc.)
                }
```

**Comment by diwakergupta** [comment]
Is this done @gregorycoppola ?

**Comment by gregorycoppola** [comment]
This was addressed in:
* https://github.com/stacks-network/stacks-blockchain/pull/2975
* https://github.com/stacks-network/stacks-blockchain/pull/3139
