### ISSUE TITLE
Add stacks tip height to http headers

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#2822]
For the `v2/health` endpoint, a node will need to determine whether it is caught up with its peer nodes (its Stacks tip height should be comparable to its peers' tip height). 

This information is currently not readily available. 

Can have a node include a `X-Stacks-Tip` header in its responses, which would contain the tip block height and block hash. This requires modification to the node's HTTP server.

**Comment by pavitthrap** [comment]
From blockchain meeting: 
We would include the stacks tip height within http headers for messages sent in the data place by default. 
We would also want to cache the tip height.

**Comment by jcnelson** [comment]
This is now in `master`.
