### ISSUE TITLE
When in IBD, only do one inv sync with the bootstrap peer(s) per reward cycle

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#2860]
When booting up a node, it will ask its bootstrap peers for block inventories repeatedly, even though it gets the same information each time.  There's no need to do this unless it's the last reward cycle on the chain.  Skipping over the block inventory sync step until there's been an empty downloader pass during IBD should address this.

**Comment by diwakergupta** [comment]
@jcnelson is this done? If not please remove the stale label, thanks!
