### ISSUE TITLE
Add support for pruning the chain

### ISSUE THREAD

**Issue by 617a7a** [stacks-network/stacks-blockchain#2863]
**Is your feature request related to a problem? Please describe.**

Similar to how Bitcoin has a `prune=1` option that removes old blocks, Stacks should have this too to save storage space on nodes. 

**Describe the solution you'd like**

An option in the config to prune chaindata via RPC or limiting it to a certain number of MiB

**Describe alternatives you've considered**

None

**Comment by jcnelson** [comment]
This shouldn't be too difficult to do.  Once a block has been processed, a node that isn't going to be relaying block data anyway could simply discard it.  However, the MARFs can't (safely) be pruned, since a new block can build off of any other prior block.
