### ISSUE TITLE
Support Taproot addresses for PoX (2.1)

### ISSUE THREAD

**Issue by 617a7a** [stacks-network/stacks-blockchain#2905]
- Taproot is a proposed upgrade to Bitcoin which will introduce several new features.
- It will integrate the Schnorr digital signature scheme into Bitcoin, upgrading Bitcoin’s core cryptography.
- Taproot builds on the SegWit upgrade to improve Bitcoin’s privacy and lower transaction fees.
- Taproot makes future Bitcoin upgrades easier by reforming Bitcoin’s scripting language.

**Describe the solution you'd like**
Enable Stackers and miners to use Taproot addresses during PoX consensus. This is additional to #2441 

**Additional context**

Some cool details on Taproot can be found [here](https://github.com/bitcoinops/taproot-workshop).

**Comment by jcnelson** [comment]
This has been merged!
