### ISSUE TITLE
Consolidate block assembly paths for miner and follower 

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#2914]
Right now, a miner and follower follow different code paths for processing a block. 
- `epoch_begin` in miner.rs 
- `append_block` in chainstate/stacks/db/blocks.rs

The goal of this issue is to consolidate this logic.

**Comment by kantai** [comment]
Related testing issue: https://github.com/blockstack/stacks-blockchain/issues/2913
