### ISSUE TITLE
Potential way to reduce number of queries needed to execute `handle_new_burnchain_block`

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#2952]
To build whole tree of ancestor blocks `handle_new_burnchain_block` is running multiple queries that returns 1 record at a time. 
https://github.com/blockstack/stacks-blockchain/blob/a783b2736b643da577275e23758247a28fca1bfe/src/chainstate/coordinator/mod.rs#L558

First it tries to find canonical chain tip:
https://github.com/blockstack/stacks-blockchain/blob/a783b2736b643da577275e23758247a28fca1bfe/src/burnchains/db.rs#L254-L258
then it process it and if there is a need it walks through all its ancestors one by one using: 
https://github.com/blockstack/stacks-blockchain/blob/a783b2736b643da577275e23758247a28fca1bfe/src/burnchains/db.rs#L260-L276

Is there any reason why it is done in a one record at a time manner?
SQLite supports recursive common table expressions, therefore I think one query that extracts everything that is needed should be much faster:
```sql
WITH RECURSIVE blocks AS (
    SELECT * FROM (SELECT * FROM burnchain_db_block_headers ORDER BY block_height DESC, block_hash ASC LIMIT 1)
    UNION ALL
    SELECT burnchain_db_block_headers.* FROM burnchain_db_block_headers
    JOIN blocks ON burnchain_db_block_headers.block_hash = blocks.parent_block_hash 
)
SELECT * FROM blocks
```
Extracting block_ops could be done using same approach with one additional JOIN.

**Comment by jcnelson** [comment]
I have a few questions about this:

* Would this change noticeably improve performance?  I think all of the queried data pulled out of sqlite with these methods ends up getting used, so there's no gain to be had by avoiding parsing data.

* Can this change be done without introducing a memory exhaustion error or a node stall?  The risk with this `WITH RECURSIVE` query is that you could end up scanning the whole burnchain database into RAM.

* The `burnchain_db_block_headers` and `blocks` tables live in different databases.  I know you can join databases together within a sqlite connection, but I don't know the performance or safety considerations of doing so (like, is a `SELECT` statement that pulls data from different databases guaranteed to be atomic with respect to ongoing writes to either database?)

**Comment by LNow** [comment]
1. I don't know Rust good enough to implement it on my own and provide you concrete answer. 
What I do know for sure it that these queries are executed a lot of times during initial synchronization, and if I'm not wrong they are not using prepared statements so every time they need to evaluated and analyzed from scratch. And query analysis and evaluation takes time.

2. Yes. If you would like to keep memory usage at very low lever then you can use `LIMIT` or `WHERE` and read no more than 50 or 100 rows at a time.

3. All queries executed within one transaction (using one DB files or multiple attached DB files) are executed atomically.
https://sqlite.org/atomiccommit.html#_multi_file_commit
https://sqlite.org/lang_attach.html


I would say that verification if you are using (and re-using) prepared statements should be first thing on the list.
Preparing query plan for simple DML is not a very expensive operation, but if you execute same query over and over again (thousands of times) it can accumulate very rapidly and cause high CPU usage.
