### ISSUE TITLE
BNS: Name renewal does not burn STX tokens

### ISSUE THREAD

**Issue by larrysalibra** [stacks-network/stacks-blockchain#2973]
The `name-renewal` function is missing the call to `stx-burn?` that would burn the required number of STX tokens to renew the name. Instead, the `stx-to-burn` argument is only checked to see that it meets the minimum amount without actually burning the tokens. The result is that you can renew names for "free" by only paying STX fees.

This is a transaction where I renewed `larry.btc` without burning any STX tokens: https://explorer.stacks.co/txid/0x55c8fb362b62ce9b46deed2884301ef5ab255581df35d5f12a71ae72eccc3015?chain=mainnet

Prior to this transaction, the expiration block was # 280342.
After this transaction confirmed, the expiration block is # 304411 - ~5 years from the confirmation block.

**Steps To Reproduce**
1. make a contract call to `name-renewal` for a name in the .btc namespace with the burn amount set to 2 STX and no post-conditions.
2. wait for the transaction to confirm
3. observe that no STX are burned

**Expected behavior**
I expect that a .btc name with price 2 STX would require 2 STX be burned to renew.

Contract source is here: https://explorer.stacks.co/txid/SP000000000000000000002Q6VF78.bns?chain=mainnet
`name-renewal` function begins at line 735.

**Comment by diwakergupta** [comment]
@jcnelson @lgalabru is this fixed in 2.1 or still an issue?

**Comment by jcnelson** [comment]
This will not be fixed, because there is no universe in which we retroactively modify a smart contract.  Such actions would de-legitimize the project.

Instead, BNSx should handle this.
