### ISSUE TITLE
Stacks' Congestion is Halting the Network

### ISSUE THREAD

**Issue by Artiume** [stacks-network/stacks-blockchain#2980]
**Describe the bug**

Since MegaPont has started to mint and release 65k NFT's on Dec. 20th, the Stacks chain has become unusable. 

Things I have noticed: MegaPont's system is DDOSing the API. Either this is via their minting process or just end users attempting multiple mints of the same NFT due to network congestion.

https://explorer.stacks.co/txid/0xc0a848e593ad4294564a6c749a81bf009afb6b7d7a6ddb7e4d6d92a86179ef90?chain=mainnet

But I am also seeing lots of issues on the Stacks side, such as the mempool. 

https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool

2773 transactions pending. And yet... We're getting blocks that are basically empty.

![FHIatkMWUAcFXJH](https://user-images.githubusercontent.com/20715731/146939377-9a93f8cc-7285-4042-a575-8e5621edc182.jpeg)

**Additional context**
Please include any relevant stack traces, error messages and logs.

Are Stacks appchains or subnets ready? There's more here than just MegaPont clogging the pipes, but we need to help these mega projects shift to better solutions than being on the main chain.

**Comment by 314159265359879** [comment]
This feat https://github.com/blockstack/stacks-blockchain/pull/2884, currently being worked on will probably help alleviate the mempool issues. 

It also looks like the issues are enlarged by bitcoin reorgs 
See this:
![image](https://user-images.githubusercontent.com/33360391/146955924-1488b126-0ccc-4f2f-a048-7260946f4872.png)

BTC blocks in rapid succession (many more minutes apart lately)
![image](https://user-images.githubusercontent.com/33360391/146955963-e4e0b575-d690-4220-83a5-c815acc3eb62.png)

And miners not getting their bids in(to the "right" fork)
![image](https://user-images.githubusercontent.com/33360391/146956040-390b8f34-86e9-43a3-ba4f-fd58043ded41.png)

**Comment by Artiume** [comment]
Awesome, thanks. Would it also improve the chances of microblocks succeeding? I've noticed how nodes don't always use the micro's in the anchor.

**Comment by jcnelson** [comment]
Feat #2884 has been merged.  There's not much we can do in an absolute sense about there being more transaction demand than block capacity (this is true of all blockchains), but the mempool has been quite for some time now, and transactions now reliably propagate between miners.
