### ISSUE TITLE
Fix flaky test `size_overflow_unconfirmed_stream_microblocks_integration_test`

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#3000]
This test has flaked twice in the past two days, for unrelated PR's

`tests::neon_integrations::size_overflow_unconfirmed_stream_microblocks_integration_test`

https://github.com/blockstack/stacks-blockchain/runs/4803981368?check_suite_focus=true

https://github.com/blockstack/stacks-blockchain/runs/4793773507?check_suite_focus=true

**Comment by jcnelson** [comment]
This isn't flaky anymore as of 2.05.0.6.0
