### ISSUE TITLE
NoEstimateAvailable error when estimating fee for contract call via v2/fee/transaction endpoint

### ISSUE THREAD

**Issue by bilalanees98** [stacks-network/stacks-blockchain#3006]
## Describe the bug

When I make a contract call with out mentioning the fees in the options, I get a NoEstimateError from the v2/fees/transaction endpoint. 
The error:
` Error estimating transaction fee. Response 400: Bad Request. Attempted to fetch https://stacks-node-api.testnet.stacks.co/v2/fees/transaction and failed with the message: "{"error":"Estimation could not be performed","reason":"NoEstimateAvailable","reason_data":{"message":"No estimate available for the provided payload."}}`

## Steps To Reproduce

The code I run is as follows
` 
const NETWORK = new StacksTestnet();
const sponsored = false;
const nonce = 0;
const tx_options = {
  contractAddress: "ST000000000000000000002AMW42H",
  contractName: "bns",
  functionName: "name-preorder",
  functionArgs: [bufferCVFromString(/*domain_name_hash*/), uintCV(2000000)],
  validateWithAbi: true,
  network: NETWORK,
  postConditions: 2000000,
  senderKey: //private_key,
  sponsored,
  nonce: typeof nonce === "number" ? new BN(nonce) : nonce,
};

const transaction = await makeContractCall(tx_options);

I have tried this out with sponsored=true, but I get the same error.

Note: I DONOT get an error when making a simple stx-transfer call (with no fees mentioned)

## Expected behavior

The makeContractCall function should return a StackTransaction

## Environment

 - OS: MacOS
 - Using Stackjs v 3.1.0

## Additional context

Error stack: 
`    at estimateTransaction (/Users/tintash/bilal retrytx/retrytx/node_modules/@stacks/transactions/dist/builders.js:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async makeUnsignedContractCall (/Users/tintash/bilal retrytx/retrytx/node_modules/@stacks/transactions/dist/builders.js:389:23)
    at async makeContractCall (/Users/tintash/bilal retrytx/retrytx/node_modules/@stacks/transactions/dist/builders.js:407:29)`

**Comment by jcnelson** [comment]
Hey, this is expected behavior.  The node does not yet have enough data to estimate a fee for calling this particular contract function.
