### ISSUE TITLE
stacks-node does not broadcast new block

### ISSUE THREAD

**Issue by CharlieC3** [stacks-network/stacks-blockchain#3015]
**Describe the bug**
The stacks-node does not attempt to broadcast a new block if shutdown is requested soon after receiving the new block. This can cause database corruption in a stacks-blockchain-api instance.

![Screen Shot 2022-01-24 at 11 47 40 AM](https://user-images.githubusercontent.com/2747302/150826977-15195ba3-89e8-443e-9132-9b5be8126376.png)

**Steps To Reproduce**
Terminate a stacks-node right after it receives a new block.

**Expected behavior**
The stacks-node should only exit after completing any pending broadcasting steps successfully.

**Comment by kantai** [comment]
Pretty related: https://github.com/stacks-network/stacks-blockchain/issues/2813

**Comment by jcnelson** [comment]
It seems that the node should not terminate until it has no blocks to process (or no events in general)

**Comment by CharlieC3** [comment]
A suggested workaround during the blockchain meeting on Jan 24th was to cut off network traffic to the stacks-node before shutting it down. I've found that the issue can still happen even if network traffic is cut off (except traffic between the stacks-node and the API) for **30 seconds** before requesting the stacks-node to terminate.

I'm going to increase the delay between cutting off network traffic to requesting termination to **120 seconds** this week and will report the results again next week.

**Comment by jcnelson** [comment]
Problems still happen as late as 5 minutes after cutting off network traffic.

We need to loop in the termination handler into the coordinator so it stops processing blocks.  Namely, the stacks chainstate should not commit a block once termination has been received, even if it was in the middle of processing it.

**Comment by jcnelson** [comment]
In addition, the node should not mark a block as processed until its events have been broadcasted.  I'm not sure how big of a refactor this will be.

**Comment by gregorycoppola** [comment]
@kantai @jcnelson does anyone have code pointers for this?

**Comment by kantai** [comment]
Though, I believe that @pavitthrap started some work on this issue, so I would recommend checking on that before starting.

**Comment by CharlieC3** [comment]
@pavitthrap Should this be closed? Looks like the PR didn't auto-close it.

**Comment by kantai** [comment]
Yeah, this should close.
