### ISSUE TITLE
Need help to disassemble transaction format

### ISSUE THREAD

**Issue by oOo1130** [stacks-network/stacks-blockchain#3028]
Dear everybody.
I'm new to blockchain, and fan of this aspect.
I need help urgently from all of you.
I'm going to disassemble transaction format.
Transaction looks like as following: 
8080000000040015c31b8c1c11c515e244b75806bac48d1399c77500000000000000000000000000000000000127e88a68dce8689fc94ff4c186bf8966f8d544c5129ff84d95a2459b5e8e7c39430388f6c8f85cce8c9ce5e6ec1e157116ca4a67d65ab53768b25d5fb5831939030200000000000516df0ba3e79792be7be5e50a370289accfc8c9e03200000000000f424068656c6c6f20776f726c640000000000000000000000000000000000000000000000
How can I disassemble above transaction?
In attachment, I described sample of transaction format.
![image (1)](https://user-images.githubusercontent.com/91327397/151872005-35403eab-2122-498a-9776-bd372300ba3c.png)

**Comment by jcnelson** [comment]
Hi, you should use the https://github.com/hirosystems/stacks.js/ repository for this.  It contains all the client-side tools for encoding and decoding transactions.
