### ISSUE TITLE
[burnchain] Try multiple Bitcoin peers for blocks

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3039]
Once the Bitcoin indexer has the block headers, it should gather `Addr` messages and try to contact new Bitcoin peers for blocks.  This would alleviate pressure on Hiro's hosted Bitcoin node.  The code would probably want to perform a few basic heuristics to select performant nodes as well.

**Comment by mardi00** [comment]
I'm not sure if it's related, but I thought it could be interesting to allow the definition of multiple nodes in the configuration for the burnchain.

**Comment by jcnelson** [comment]
This is not necessary now that we fetch whole reward cycles of Bitcoin blocks at once.  This significantly reduces the I/O portion of sortiiton latency.
