### ISSUE TITLE
[chainstate] implement cache strategies for nodes in tries that are persisted to disk

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3042]
Once a trie is stored to the MARF, it will never be modified.  We should be able to fearlessly cache any/all of its nodes in RAM.  The trie storage system should be updated to support a variety of caching strategies, which the user can choose in the config file (i.e. to trade RAM for speed).  At a minimum, we should support the following:

* No-op (the default; what happens now)
* Everything (keep all nodes in RAM -- useful for miners)
* Node256 (keep `TrieNode256`'s in RAM, but nothing else)

I've tried all of the above.  `Node256` offers decent performance without eating your RAM, for example.

**Comment by gregorycoppola** [comment]
Related: This issue is the line of work suggested in #3014, which suggests looking for ways to cache the MARF in RAM to improve performance.
