### ISSUE TITLE
[stacks 2.1] expose BTC/STX exchange rate in Clarity 

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3043]
We know how much BTC was spent to mint a Stacks block, and we know how much STX was produced / acquired in it.  This information could be exposed in `get-block-info?`.

**Comment by gregorycoppola** [comment]
I like this feature. I like that we can get the exchange rate without looking off chain.

Using this exchange rate, a miner could stake STX to collateralize a BTC withdrawal.

And if they try to steal the BTC, they can be penalized in STX by the Stacks chain.

**Comment by MarvinJanssen** [comment]
Could be very useful. 😁

**Comment by igorsyl** [comment]
I would not call this ratio an exchange rate given miners expect a premium. This ratio could differ from market-based exchange rate by more 10%.

**Comment by jcnelson** [comment]
Miners spend X BTC, and get Y STX, and this information is now reported to Clarity.  `get-block-info?` now reports X and Y on request, so I closed this issue.

Also, this is _factually_ the exchange rate.  Just because an exchange says something different doesn't make it true; the only thing that matters here is what happens on-chain.

**Comment by gregorycoppola** [comment]
@jcnelson What if there is an on-chain market for BTC/STX.. can we get the rate from there?

**Comment by jcnelson** [comment]
Sure -- this would be the way to get that exchange rate.

**Comment by gregorycoppola** [comment]
I mean where people are literally (trustlessly) trading STX for BTC.. without anyone being a miner.

Just a market.
