### ISSUE TITLE
[chainstate] memoize block-commit descendancy information for `SortitionHandleTx::descended_from`

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3045]
The method `SortitionHandleTx::descended_from` is particularly slow, since it can do *lots* of MARF reads in the sortition DB.  Looking at the log files, it seems to be the biggest contributor to sortition-processing -- even more so than downloading the Bitcoin block!  Fortunately, we can easily memoize the PoX anchor block that a block-commit descends from; this should remove the need to query the MARF at all.

**Comment by gregorycoppola** [comment]
Related: This issue is the line of work suggested in https://github.com/stacks-network/stacks-blockchain/issues/3014, which suggests looking for ways to cache the MARF in RAM to improve performance.
