### ISSUE TITLE
Miner misses non-flash bitcoin blocks

### ISSUE THREAD

**Issue by MaksimalistT** [stacks-network/stacks-blockchain#3058]
**Describe the bug**
Miner misses non-flash bitcoin blocks
some examples
#724071
724071 comes 2 min after 724070 but there was not commit to 724071
Miner commits: 
https://btc.com/btc/transaction/1b586fb201479d74e0be9ce1307c518d2ac9d1d0c5c1b946a74a91c3377f620f
https://btc.com/btc/transaction/40e413e63ed8a42697e4a8f5bd79b3aa72f5db7ed6e6c8e6d5451c53c38490e5

#724063
724063 comes 2 min after 724062 but there was not commit to 724063
Miner commits: 
https://btc.com/btc/transaction/a7708a9c32cbd171401707a97cdf7338ca113814d9079da58b01696a1cd8ab5e
https://btc.com/btc/transaction/461d3fd38649441b6bd2ab81a91710fb89a4151ae9de0b7459d1f3a3f7864206

**Steps To Reproduce**
**stacks-node config**
[burnchain]
...
poll_time_secs = 1

[miner]
first_attempt_time_ms = 1
subsequent_attempt_time_ms = 180000
microblock_attempt_time_ms = 30000

**bitcoind config**
[core]
txindex=1
prune=0
maxorphantx=1
banscore=1

**Expected behavior**
Miner doesn't miss non-flash blocks, like some other miners

**Environment (please complete the following information):**
- OS: Amazon Linux
- Rust version: rustc 1.58.1
- Stacks-node 2.05.0.1.0

**Additional context**
I assume stacks-node lagging to sync with burnchain or bitcoind lagging to sync latest blocks
could you please help to localize an issue or provide some recommendations to fix it
if there is foundation miner which shows better performance, where is it located? and what configurations is used for stacks-node and bitcoind? is there a list of robust bitcoind peers?
appreciate any help, thanks.

**Comment by jcnelson** [comment]
Hey, thanks for the report.  As with other issues, I'm going to need to see the debug logs to figure out what's going on.  Also, what version of the node software are you running?  2.05.0.1.0 brings a lot of fixes to the miner.

**Comment by MaksimalistT** [comment]
Hi, @jcnelson 
i am running latest version 2.05.0.1.0
here is the latest missed blocks and debug log
724185-49550 and 724253-49613 missed
https://watcher-data.s3.amazonaws.com/724185-49550.log.gz
https://watcher-data.s3.amazonaws.com/724253-49613.log.gz

**Comment by MaksimalistT** [comment]
Hi, any updates on this?

**Comment by jcnelson** [comment]
Hi, sorry for the delay.  I hope to get to this this week (I've been on leave).

**Comment by jcnelson** [comment]
Hey, I've taken a look at the two logfiles:

In the first case, the miner attempted to mine block 49550 (Bitcoin block 724185) a total of 5 times, with a targeted Bitcoin block height of 724186.  The final transaction sent was `7bffd8ef9f57101e61027a2afdbfcc97832c77e7306ee945c7e50755215323ae`, and it was mined in Bitcoin block 724186, as desired.  Per the logfile, the Stacks node treated it as a valid block-commit for block 724186.  It didn't miss the block here.

In the second case, the miner attempted to mine block 49613 only once.  The transaction ID was `121ad4cde98c7d635ded123280659910456e2c02b22382facc692771936e68fe`, with a target Bitcoin block height of 724253.  However, this transaction was mined by Bitcoin miners in 724254, so the Stacks node treated this block-commit as a late block commit.  Looking at the order of events, the node discovered Bitcoin block 724252 at local UNIX epoch time `1645404670.913661`, it sent the block-commit at `1645404698.019325` local UNIX epoch time (about 28 seconds later), and it discovered Bitcoin block 724253 at `1645404707.598623` local UNIX epoch time (about 7 seconds after sending the block-commit).  Between sending the block-commit and discovering Bitcoin block 724253, it had been polling the Bitcoin node for new blocks every second (per your config), so the miner had believed that the block-commit transaction it sent would be picked up.  It seems that Bitcoin miners simply didn't include it in the desired block.

**Comment by MaksimalistT** [comment]
@jcnelson
sounds like 724253 was discovered significantly later than it could be
does it mean that bitcoind node sync is lagging? do you have any recommendations on how to improve it?

**Comment by MaksimalistT** [comment]
Hi, @jcnelson 
miner keeps missing bitcoin blocks regularly, what would you recommend to mitigate the issue?

**Comment by jcnelson** [comment]
The second case does not happen in 2.05.0.6.0 -- the arrival of a new Bitcoin block would prevent the miner from finishing the block.  My advice would be to upgrade to this release (or 2.1.0.0.0 if you have time to run a genesis spin-up).

Going to close due to inactivity.
