### ISSUE TITLE
[Clarity] only charge for a contract-load once in a transaction's execution

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3061]
Right now, the Clarity VM naively charges a transaction for the cost of loading a contract each time it is called, even if it is called multiple times over the lifetime of the transaction.  Instead, the VM could cache already-loaded contracts once they are accessed for the lifetime of the transaction.

A particularly big pain-point that this would address right now is that invoking a `contract-call?` via a `fold`, `map`, `filter` will incur a very high runtime cost.  This effectively precludes implementing the equivalent of `send-many` for SIP 010 contracts, for example, because the act of running `contract-call?` to `transfer` via a `fold` would be prohibitively expensive.

**Comment by LNow** [comment]
I think #2816 covers the same problem.

**Comment by jcnelson** [comment]
Yup; closing in favor of #2816
