### ISSUE TITLE
Non-critical type-checker bug related to traits

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3064]
**Describe the bug**
The type checker cannot properly handle the case where a trait defined in the same contract is used. The error that it reports is also incorrect.

**Steps To Reproduce**
Consider these two contracts:

bar.clar:
```clarity
(define-public (hello (a int))
    (ok u0)
)
```

test.clar:
```clarity
(define-trait my-trait
    ((hello (int) (response uint uint)))
)
(define-private (pass-trait (a <my-trait>))
    (print a)
)
(define-public (call-it)
    (ok (pass-trait .bar))
)
```

The type-checker will report an error on the call to `pass-trait` indicating the use of an unresolved contract "bar". However, the actual error is that it is unable to find the trait "my-trait", because the type-checker only checks in the analysis database, but since this trait is in the current contract, it is not yet in the database. It could, instead, be found in the `ContractAnalysis`.

The simple workaround is to only use a trait in a separate contract from where it is defined, but I don't think that is an intended restriction. Fixing this would be consensus-breaking, so it should be considered for 2.1, or if this is the intended behavior, it should be documented.

The problem with the error that is printed can be fixed with a patch similar to [this commit in the REPL](https://github.com/hirosystems/clarity-repl/commit/ecfad3a474f7996356eb6140f3262615557334b4).

**Expected behavior**
I expect this contract to pass type-checking.

**Comment by obycode** [comment]
#3065 fixes the problem with the error message.

**Comment by jcnelson** [comment]
Thanks for sending the PR! Going to go ahead and close this.
