### ISSUE TITLE
Create list of most common log entries generated by `stacks-node`

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#3089]
**Is your feature request related to a problem? Please describe.**
Whenever I have some problems with `stacks-node` I have to collect logs and share them with core developers, so they could analyze them and help me find out what is wrong.

**Describe the solution you'd like**
I'd love to have access to at least part of the core developers knowledge about which logs entries are important, which are just a noise and can be ignored, what are the most common entries and what they mean.

A good start would be a list of most common log entries generated by `stacks-node` with information what they mean, if they can or can't be ignored, their importance, if they are always present etc.
Rough dev notes that some developers might already have or short description of their strategies how to analyze logs would be also helpful.

If some problems can be diagnosed and solved by simply checking what logs are or aren't produced by `stacks-node`, then it is worth to write down this knowledge.

**Comment by jcnelson** [comment]
Part of this is that some things that aren't serious enough to log (especially in the network stack) are still getting logged.

**Comment by jcnelson** [comment]
Do you have specific log items you're confused about?  We should open issues for each such confusing log entry in order to make them less confusing.

**Comment by LNow** [comment]
> Do you have specific log items you're confused about?

I'd say majority of log items are cryptic.

To give you an example. This is an entry that is repeated over and over again when node is still synchronizing:
```
WARN [1649709186.078155] [src/net/p2p.rs:5159] [relayer] Transaction rejected from mempool, {"error":"transaction rejected","reason":"TooMuchChaining","reason_data":{"actual":18713,"expected":6512,"is_origin":true,"message":"Nonce would exceed chaining limit in mempool","principal":"SP3WV3VC6GM1WF215SDHP0MESQ3BNXHB1N6TPB70S"},"txid":"df1cb9f85ba9225d359a44238838793c0bf1810f47b01a46d1f188f6a7349d02"}
```
` [src/net/p2p.rs:5159] [relayer] ` suggests that entry was generated in `p2p.rs` file in section/execution path `relayer`, so the simplest conclusion is that my node received information about transaction that has been rejected from mempool in different node. But it doesn't make any sense. Why different node would inform my node about TX rejected from mempool?
Maybe it was my node that rejected TX? If that's the case, why it has been reported in `[src/net/p2p.rs:5159] [relayer]`? And why my node is trying to process the transactions if it is still out of sync?

Another example:

```
WARN [1650301666.948017] [src/chainstate/burn/operations/leader_block_commit.rs:672] [chains-coordinator] Invalid block commit: missed target block, intended_modulus: 2, actual_modulus: 3, block_height: 666823, apparent_sender: 1Frf72kABGpEwEmPUGwsUbvJ2odenr3TRg
WARN [1650301666.948193] [src/chainstate/burn/db/processing.rs:61] [chains-coordinator] REJECTED(666823) leader block commit 1ae6cef074915db55c2de0d5afef4d00d644c7b8e31fa773d31702d9ab3df02c at 666823,84: BlockCommitNoParent
WARN [1650301666.948243] [src/chainstate/burn/operations/leader_block_commit.rs:672] [chains-coordinator] Invalid block commit: missed target block, intended_modulus: 2, actual_modulus: 3, block_height: 666823, apparent_sender: 16sAXi1jxhxKCfY84hubDdnFNaAhqd5t49
WARN [1650301666.948363] [src/chainstate/burn/db/processing.rs:61] [chains-coordinator] REJECTED(666823) leader block commit 5957ee9bfe77b5faf8ef502853eeac03fedabebaf00af99a3befcf5d10b095a7 at 666823,85: BlockCommitNoParent
WARN [1650301687.219081] [src/chainstate/burn/operations/leader_block_commit.rs:672] [chains-coordinator] Invalid block commit: missed target block, intended_modulus: 1, actual_modulus: 2, block_height: 666837, apparent_sender: 1GLHxpjk6uAWCSYnPiYZX9hPu28HrZ1xVF
WARN [1650301687.219227] [src/chainstate/burn/db/processing.rs:61] [chains-coordinator] REJECTED(666837) leader block commit 234bd7924edf143ac55cad3472307761116d4a954b1b3c86b42321ccfcce7448 at 666837,193: BlockCommitNoParent
```
Is my node running fine if it produce entries like this? Should I be worried? Or maybe something is wrong with on-chain data?
What the hell is `modulus`?

Try to open any log file that you have access to, and analyze it one entry at a time. Does it need to be printed? Is it expressive enough to tell ordinary user what is going on? Can it be used to troubleshoot problems with node? Can it be ignored by user?

You have the knowledge to tell which entries can or should be ignored because they are just a noise. You know if certain warning is something users should be worried about or not. You know what entries to look for to troubleshoot certain problems with node.
I want you to share this knowledge with us, users.
