### ISSUE TITLE
How to connect two nodes using only local network?

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#3093]
I'm running node in a place where I only have access to metered internet connection.
I want to run few nodes in local network where only one node have access to internet connection and all remaining nodes are connected with each other using secure local network.

How can I do that?
What configuration options should I use?

**Comment by jcnelson** [comment]
Hey @LNow, you may need to set the `p2p_address` field in `[node]` to force it to use the internal IP address.

**Comment by LNow** [comment]
Hey @jcnelson , thank you!
With `p2p_address` I managed to connect 2 nodes using local IP address. 

Is there an option which I could use to list of IP addresses my node can connect to? It tries to connect public nodes, and I'd like to keep it connected only to a very specific local nodes.

**Comment by jcnelson** [comment]
> Is there an option which I could use to list of IP addresses my node can connect to? It tries to connect public nodes, and I'd like to keep it connected only to a very specific local nodes.

Not currently.  But, you can prevent your node from connecting to or listening to other hosts with `iptables` or equivalent.

**Comment by LNow** [comment]
I was hoping that somehow I could avoid messing with `iptables`.
Thanks.
