### ISSUE TITLE
[clarity] All check errors must be handled as runtime errors

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3107]
Right now, `(at-block)` can emit `CheckError`s which cause the transaction to be invalid, as well as the block that includes it.  In Stacks 2.1, we should make it so that _any_ error emitted by `(at-block)` is a `RuntimeError`, so at least the transaction will be mineable and fees will be collected.

**Comment by jcnelson** [comment]
N.B. this applies to all check errors.  We should not merely re-cast all check errors as runtime errors, but instead treat check errors the way we do for runtime errors -- i.e. they don't invalidate the block; they only debit the sender the tx fee (but the tx receipt should contain the original check error).

**Comment by saralab** [comment]
A good one for @obycode to help with.

**Comment by obycode** [comment]
👍 I just finished reviewing the PR.

**Comment by jcnelson** [comment]
I already did this one @saralab.

Thank you for your review @obycode!
