### ISSUE TITLE
[Clarity] need a `.costs-3` contract for Stacks 2.1 and associated benchmarking

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3115]
Stacks 2.1 adds new Clarity functions, which will need their own cost functions, which in turn necessitates a `.costs-3` contract and associated benchmarks.

**Comment by jcnelson** [comment]
Making a list:

* `to-consensus-buff`: _O(n)_ in the size of the value
* `from-consensus-buff`: _O(n log n)_ in the number of atoms in the type signature (caused by tuple key/value pairs needing to be in sorted order).

**Comment by saralab** [comment]
@jcnelson : @pavitthrap can pick this up once she's back next week, she has prior experience with the costs contract benchmarking and can help with this.
Let me know if I can mark her as the assignee here .

**Comment by obycode** [comment]
Adding a note to mention that we may want to add a new, separate cost function for parsing with the v2 parser, as it is significantly cheaper than the original parser.

**Comment by a3slade** [comment]
> Making a list:
> 
> * `to-consensus-buff`: _O(n)_ in the size of the value
> * `from-consensus-buff`: _O(n log n)_ in the number of atoms in the type signature (caused by tuple key/value pairs needing to be in sorted order).

I'm not seeing where any sorts are occurring. And perhaps I'm misunderstanding what's happening here, but wouldn't that occur in the serialization?

I don't see runtime_cost called at all from to-consensus-buff. Is it supposed to be or does that n get passed in from somewhere else? In from-consensus-buff it's called with n=the len of the input bytes in the buffer but from Jude's comment that doesn't sound like the n we want (if there is a sort somewhere).

**Comment by jcnelson** [comment]
`from_consensus_buff` can parse a tuple, and tuple key/value pairs are
stored in an ordered map (a `BTreeMap`), which means loading a Clarity
value can take as long as O(n log n) for n bytes.

**Comment by a3slade** [comment]
okay, if you're happy then I'm happy.

**Comment by a3slade** [comment]
did you see my other question (re: slices and whether they should be O(n) wrt right_position - left_position? Because if you're okay with that being O(1) then I'm ready to lgtm.

**Comment by saralab** [comment]
To Do: 
- Rebase from next branch and re-run the benchmarking

**Comment by jcnelson** [comment]
So in total we need:

* `replace-at?`
* `AnalysisFetchContractEntry` (thanks @obycode!)
* `as-contract`
* Comparator functions on sequences

**Comment by jcnelson** [comment]
Merged!
