### ISSUE TITLE
Stacks 2.1 cost benchmarks: `to-consensus-buff` and `from-consensus-buff`

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3138]
We need to add cost functions and benchmarks for `to-consensus-buff` and `from-consensus-buff`.

I believe that both of these methods are linear: `to-consensus-buff` in the size of its argument, and `from-consensus-buff` in the size of its second argument.

**Comment by jcnelson** [comment]
For `from-consensus-buff`, the runtime is _O(n log n)_ due to tuple keys needing to be stored in sorted order in a `BTreeMap`.

**Comment by jcnelson** [comment]
Closing in favor of #3115
