### ISSUE TITLE
`slice` result doesn't change length on buffer type

### ISSUE THREAD

**Issue by hstove** [stacks-network/stacks-blockchain#3141]
**Describe the bug**
In the `next` branch, the `slice` function doesn't change the resulting type of the buffer to reflect the new max length. My expectation is that the result would have a new typed length that reflects the `start` and `end` params to the `slice` function.

If you use `use-max-len?` with `slice`, you can achieve this result, but it seems like redundant code and cost.

**Steps To Reproduce**

The output of this function is a `(buff 32)`:

```clarity
(define-read-only (basic-slice (b (buff 32)))
  (slice b u0 u12)
)
```

**Expected behavior**

The output of this function is `(buff 12)`, which is what I'd expect `slice` to do automatically:

```clarity
(define-read-only (slice-as-max-len (b (buff 32)))
  (unwrap-panic (as-max-len? (slice b u0 u12) u12))
)
```

**Context**

I'm evaluating this by using `clarity-cli` compiled on the `next` branch, with some minor tweaks to support Clarity2 functions.

**Comment by jcnelson** [comment]
Per the blockchain meeting, the slice length can be variable, so this isn't a bug.
