### ISSUE TITLE
Bad tx receipts when contract deployment top-level code fails

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-blockchain#3154]
**Describe the bug**
A contract is deployed successfully, even though the top-level code in the contract contains errors.

**Steps To Reproduce**
1. Deploy a contract with a function that can fails
2. Deploy a contract that calls the first contract's function as top-level code so that the first contract fails
3. Deploy another contract that calls the first contract's function as top-level code so that the first contract fails but with the contract call wrapped in `try!`
4. Deploy another contract that calls the first contract's function as top-level code so that the first contract fails but with the contract call wrapped in `unwrap-panic`

Successful contract deployments with contract calls that fail and succeed and with wrapping in `try!` and `unwrap-panic`:
* https://explorer.stacks.co/txid/0x3ebf410f601e0a837791e1c5119a7921c5971af5be0499328da2454445f2b6db?chain=testnet
* https://explorer.stacks.co/txid/0xfd452e1507bcd5303e662e53f68698f64fb9f2e83471cf24c794e31ec0b2d611?chain=testnet
* https://explorer.stacks.co/txid/0x60cc62cfd6afb1d364efde72f254275e610d0de977142f560dbd0a3efa4954cd?chain=testnet
* https://explorer.stacks.co/txid/0x54483249f857918d59a086ba6d632142b3eb53b80e4830b252ce06fa0926f9e3?chain=testnet
* https://explorer.stacks.co/txid/0xfc88243a3ac8f97ae914e412bec91a50ce2a9276d8dd712662fdae7112377aaa?chain=testnet
* https://explorer.stacks.co/txid/0xd03884c0305cfe18cbd8ba910ad9ff49c024ec638fee127924d5ca3bb7dcbc6d?chain=testnet
* https://explorer.stacks.co/txid/0x9e7efe23e27b3c587b70550cd8e18956e44af00cf6dd91f59ca28927f5a1bc97?chain=testnet

**Expected behavior**
A contract deploy transaction should only succeed if and only if the code is correct and all top-level statements do not throw errors and do not return err responses.

**Additional context**
This was discovered during prize distribution of the 90stx raffle, e.g. https://explorer.stacks.co/txid/0x5421e0963f29b4409718b2f864262aee559f00ccc8edc302bf274d9cea98c320?chain=mainnet

**Comment by kantai** [comment]
When top-level code in a contract publish causes a runtime error, the transactions should be accepted, but the contracts should not be created, and I believe that's what's happening here:

The example

https://explorer.stacks.co/txid/0x082cbff84db2e95dcfba29ed770f61422729e3a8d1a0f2930fc30f5705db2466?chain=testnet

doesn't result in a contract that exists -- you could republish the contract.

The reason that the transaction still is accepted is the same reason that runtime errors in other kinds of transactions still get included in a block (miners need to get paid for the cost of evaluation up to the error).

It does seem like the explorer and API really don't like these contract publish errors though (they don't actually show up as errors in the API, and when you do issue a republish, the chain of transactions looks pretty weird. You can see the chain of transactions on this address is pretty weird: 

https://explorer.stacks.co/address/ST27NDPAAKRW73RHAQYCC7WM7G4NFS0YASX5SY1VT?chain=testnet

The fault for this rests with the stacks-node implementation, though, so I think we should keep this issue open, with a plan for a two-part remedy:

1. Document the behavior of runtime errors in top-level contract code (probably here: https://github.com/stacks-network/docs/blob/master/src/pages/en/write-smart-contracts/overview.md)
2. Fix the transaction receipts returned in this case, I think it's a pretty straight-forward fix:

```diff
diff --git a/src/chainstate/stacks/db/transactions.rs b/src/chainstate/stacks/db/transactions.rs
index 319ccb241..7bffc52d1 100644
--- a/src/chainstate/stacks/db/transactions.rs
+++ b/src/chainstate/stacks/db/transactions.rs
@@ -1049,7 +1049,18 @@ impl StacksChainState {
                                       "contract" => %contract_id,
                                       "code" => %contract_code_str,
                                       "error" => ?error);
-                            (AssetMap::new(), vec![])
+                            let receipt = StacksTransactionReceipt {
+                                transaction: tx.clone().into(),
+                                events: vec![],
+                                post_condition_aborted: false,
+                                result: Value::err_none(),
+                                stx_burned: 0,
+                                contract_analysis: Some(contract_analysis),
+                                execution_cost: total_cost,
+                                microblock_header: None,
+                                tx_index: 0,
+                            };
+                            return Ok(receipt);
                         }
                         ClarityRuntimeTxError::AbortedByCallback(_, assets, events) => {
                             let receipt =
```

**Comment by jcnelson** [comment]
@kantai I see you have a commit that fixes it, but I don't think it ever landed in `master`?  If so, do you want to make a PR for it?

**Comment by kantai** [comment]
Yep, I'll revive that PR
