### ISSUE TITLE
Whitespace between expressions?

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3158]
The parser reports an error when there is no whitespace between two expressions, e.g.:

```clarity
(concat "a " " b")(concat "r" "d")
```

This results in:

```
error: Expected whitespace or a close parens. Found: '('
```

(This was noticed by @fariedt in hirosystems/clarity-repl#158)

The new parser (#3150) currently allows this pattern. Any objections to allowing this after the 2.1 epoch, along with the other parser consensus-breaking changes?

**Comment by jcnelson** [comment]
If the new parser is coming in 2.1 anyway, then fixing it then and there is fine by me.

**Comment by obycode** [comment]
The whitespace rules are more reasonable and less surprising with the new parser in 2.1.
