### ISSUE TITLE
[clarity] support decoding unescaped characters in utf8 strings via `from-consensus-buff`?

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3169]
When looking through how `from-consensus-buff` works, I noticed that while decoding a buffer representation of an ASCII string, the VM will require that all bytes represent punctuation, alphanumerics, or whitespace (this happens via `Value::string_ascii_from_bytes()`).  In other words, you can't decode an ASCII string that contains e.g. control codes.

I noticed that no such checks are applied for decoding a UTF-8 string from bytes (i.e. `Value::string_utf8_from_bytes()`).  Is this deliberate?  Should I be allowed to instantiate a unicode string in Clarity with non-printable characters, even if it's only using ASCII characters and not UTF-8 codepoints?

**Comment by kantai** [comment]
This is deliberate, yes. The ASCII type in Clarity isn't "all ASCII characters" -- constructors for ASCII types in Clarity check for non-control ASCII characters: you can't construct ASCII values with those characters either through deserialization or through literals. The UTF8 type, however, is designed to permit any UTF-8 characters.

**Comment by jcnelson** [comment]
Gotcha. Thanks for clarifying :pray:
