### ISSUE TITLE
Panic in Clarity contracts should provide a meaningful error message

### ISSUE THREAD

**Issue by njordhov** [stacks-network/stacks-blockchain#3177]
Panic in Clarity contracts results in a useless and uninformative `(err none)` reported to the caller when the contract aborts, whether triggered by `unwrap-panic` or a failure such as an [uint subtraction underflow](https://explorer.stacks.co/txid/0x7b2817c2ecd8fbf66805ec8d7424cb2a982f8e906d73856dd9906deae409355a?chain=testnet).

Instead, a *panic* should provide a useful error message so the caller can understand why the contract call was aborted.

The lack of helpful panic messages leads to confused developers, ad-hoc workarounds, and avoidance of `unwrap-panic`, an anti-pattern. The [clarity-lang book](https://book.clarity-lang.org/ch06-03-unwrap-flavours.html ) even explicitly advises against using `unwrap-panic` due to the lack of a useful response:

> You should ideally not use the -panic variants unless you absolutely have to, because they confer no meaningful information when they fail. A transaction will revert with a vague "runtime error" and users as well as developers are left to figure out exactly what went wrong.

See also:
* https://github.com/stacks-network/stacks-blockchain/issues/2877
* https://github.com/clarity-lang/reference/issues/26
* https://github.com/clarity-lang/reference/issues/25

**Comment by jcnelson** [comment]
Hey @njordhov, are you asking that the _transaction receipt_ include something more informative than `(err none)`?  Because if so, this isn't a breaking change, and could be done in the next release.  Please elaborate?

**Comment by njordhov** [comment]
@jcnelson Yes, it's about making the transaction receipt more informative on Clarity panics. Minimally, it should provide an error message with the specific reason for the failure, or the triggering error for `unwrap-panic`. Better, a record (aka tuple) with more details including the name of the function in which the panic occurred and the location in the contract code of the failing call.

**Comment by jcnelson** [comment]
Temporarily assigning to @obycode.  Feel free to re-assign :)
