### ISSUE TITLE
Consider: Allow trait reference inside of optional

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#3179]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to put a trait reference inside of an `optional` in Clarity. This led to a lot of copy-and-pasting of code in a recent PR in the hyperchains repo. https://github.com/hirosystems/stacks-hyperchains/pull/121

While a deep refactor might have been possible, the simplest solution that came to mind would have been possible if we could put a trait reference inside of an optional.

**Describe the solution you'd like**
The following code passes in `clarinet check`, but doesn't actually work in `clarinet test` or on the test net (@obycode).

We should consider making this work:

```
(define-public (takes-optional-trait (b (optional <baz>)))
  (match b b1 (ok true) (err u100))
)
(define-public (wrapper (b <baz>)) (takes-optional-trait (some b)))
(define-public (caller) (wrapper .bar))
```

In particular, we want the method `takes-optional-trait` to work.

The current error message is:

```
Runtime error: hyperchains::withdraw-ft-asset(u1, 'ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC, none, 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.simple-ft, 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.simple-ft, 0xba8a9d7d8032c5c84b8b1b686e9db6318c3e3346fb8b8352433576a836ef6f1e, 0xa8ce97c4e7676322d5f7e1edb822f37d7dd58cc7292223d07dae0a378b5222d5, (list { hash: 0xa67e38b0202eb5e8cb9da3ed2a450214c473c7e9d6a8d90a64903b7244587422, is-left-side: true } { hash: 0x7d87918014ba4fc7e1c870a128b0ca8245f5fee72f4981ffee30a50eafb4c079, is-left-side: false })) -> Runtime Error: Runtime error while interpreting ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5.contract-6: Unchecked(TypeValueError(OptionalType(TraitReferenceType(TraitIdentifier { name: ClarityName("mint-from-hyperchain-trait"), contract_identifier: QualifiedContractIdentifier { issuer: StandardPrincipalData(ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM), name: ContractName("trait-standards") } })), Optional(OptionalData { data: Some(Principal(Contract(QualifiedContractIdentifier { issuer: StandardPrincipalData(ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM), name: ContractName("simple-ft") }))) })))
```

**Describe alternatives you've considered**
We could have more deeply refactored our code, but it seems like, in general, this could be a nice convenience for users to not force these deep refactors.

**Additional context**
See discussion in discord at: https://discord.com/channels/621759717756370964/713087894260023377/989921849318191104

**Comment by jcnelson** [comment]
If we allow this, then we will need to make sure that the trait type can be concretized before execution (e.g. if it's `none`).

**Comment by jcnelson** [comment]
This is now supported in the new trait system in 2.1 :tada:
