### ISSUE TITLE
Changing STX Mining Burn fee on the fly

### ISSUE THREAD

**Issue by opies32765** [stacks-network/stacks-blockchain#3181]
Guys,

Is there a way to change the code currently to be able to change the burn fee without re starting a miner ? I saw it mentioned by an admin on discord but i cannot find it again

Thanks in advance

**Comment by diwakergupta** [comment]
Dup of #2629 

cc/ @igorsyl

**Comment by igorsyl** [comment]
Working on it @opies32765 
https://github.com/stacks-network/stacks-blockchain/pull/3222
