### ISSUE TITLE
Miner should more aggressively re-attempt block production after first attempt

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3184]
I've observed this behavior in a mock miner, where the default values

* `first_attempt_time_ms = 5_000`
* `subsequent_attempt_time_ms = 30_000`

Lead to small block mines (i.e., only considering 9 or so transactions).

I *think* what's going on in the mock miner is that the check in `neon_node` for whether or not to attempt another block only attempts a new block if:

1. We've only tried once before (i.e., this is attempt 2) **and** the first attempt was empty.
2. There's new state to mine off of (microblocks or a newly arrived block)

The relevant case branches are roughly

https://github.com/stacks-network/stacks-blockchain/blob/master/testnet/stacks-node/src/neon_node.rs#L1720

What this means is that if the first attempt mines any transactions (even a small amount), and there's no new microblocks being produced (e.g., the last winning miner has microblock production turned off), the miner won't attempt a heavier block ever.

**Comment by diwakergupta** [comment]
Maybe @igorsyl could take this on? :) Might also be a good time to revisit the defaults!
