### ISSUE TITLE
Improvements to trait handling

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3251]
**Is your feature request related to a problem? Please describe.**
Traits are treated like a type sometimes and not other times and have some surprising behaviors with the current implementation. See discussion [here](https://github.com/stacks-network/stacks-blockchain/discussions/3231).

**Describe the solution you'd like**
My plan is to treat traits like other types, with the one limitation that they cannot be stored in a data-var or map (since this inhibits static analysis). I think that provides the least surprising behaviors and should be reasonable to implement.

**Describe alternatives you've considered**
An [alternative proposal](https://github.com/stacks-network/stacks-blockchain/discussions/3231#discussioncomment-3300350) was described in the discussion topic.

**Comment by obycode** [comment]
Changes to the behavior with this implementation (I will be appending to this list):

* A value of type `trait_A` may be passed as type `trait_B`, provided that `trait_B` is a subset of `trait_A`
```clarity
(define-trait trait-foobar
    (
        (foo () (response uint uint))
        (bar () (response uint uint))
    )
)
(define-trait trait-foo ((foo () (response uint uint))))
(define-private (call-foo (f <trait-foo>))
    (contract-call? f foo)
)
(define-public (call-foo-foobar (f <trait-foobar>))
    (begin
        (call-foo f) # This is not allowed in 2.05
    )
)
```

**Comment by obycode** [comment]
Issues #3214 and #3216 should be resolved here also.

**Comment by jcnelson** [comment]
Merged!
