### ISSUE TITLE
No block production during testnet storm

### ISSUE THREAD

**Issue by igorsyl** [stacks-network/stacks-blockchain#3252]
No testnet blocks were produced during the testnet Bitcoin storm on 2022-08-14.

Testnet metrics attached for period 2022-08-14T00:00:00-05:00 to 2022-08-15T00:00:00-05:00.

<img width="2181" alt="image" src="https://user-images.githubusercontent.com/1248500/184680897-902ed18a-f85b-4444-9619-ab54853988e0.png">

Node logs: [node-storm.log](https://github.com/stacks-network/stacks-blockchain/files/9339110/node-storm.log)

**Comment by jcnelson** [comment]
We haven't seen this issue arise again since the release of 2.05.0.6.0, which made significant improvements to the miner's ability to deal with stale Bitcoin and Stacks chain tips.  Going to go ahead and close this due to inactivity.  If the problem persists in 2.05.0.6.0, please reopen.
