### ISSUE TITLE
[Stacks 2.1] The `/v2/pox` endpoint never switches to PoX-2

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#3262]
When running with the latest `next` branch, the `GET /v2/pox` endpoint always returns `{"contract_id":"ST000000000000000000002AMW42H.pox"}` regardless of the epoch or cycle. 

The expected behavior is that this should return `{"contract_id":"ST000000000000000000002AMW42H.pox-2"}` when ready after the 2.1 epoch.

**Comment by zone117x** [comment]
As a related question: is checking for `pox-2` in the will `GET /v2/pox` response the best way for clients to determine if PoX-2 stacking contract-calls should be made?

As in, what is the recommended approach to determining if `Period 3` has activated, as described in https://github.com/stacksgov/sips/blob/c0fb33e0fc2b62e8e6d4ed85fb4b4aa289bb6042/sips/sip-015/sip-015-network-upgrade.md#specification

Right now, it seems like the work-around for clients is something like:
```ts
async function isPoX2Ready(): Promise<boolean> {
  const req = await fetch(`/v2/data_var/ST000000000000000000002AMW42H/pox-2/configured?proof=0`);
  const body = await req.text();
  if (req.ok) {
    return JSON.parse(body)['data'] === '0x03'; // Clarity boolean-true
  } else if (req.status === 404 && body === 'Data var not found') {
    return false;
  } else {
    throw new Error(`Unexpected response: ${req.status} - ${body}`);
  }
}
```

**Comment by jcnelson** [comment]
This code simply hasn't been written yet.

**Comment by zone117x** [comment]
This was fixed in https://github.com/stacks-network/stacks-blockchain/pull/3278
