### ISSUE TITLE
[costs] cost functions in costs-2 cannot be voted on via the cost-voting contract

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3268]
I noticed this block in `clarity/src/vm/costs/mod.rs` when processing a new cost function proposal:

```rust
        if target_contract == boot_code_id("costs", mainnet) {
            // refering to one of the boot code cost functions
            let target = match ClarityCostFunction::lookup_by_name(&target_function) {
                Some(ClarityCostFunction::Unimplemented) => {
                    warn!("Attempted vote on unimplemented cost function";
                              "confirmed_proposal_id" => confirmed_proposal,
                              "cost_function" => %target_function);
                    continue;
                }
                Some(cost_func) => cost_func,
                None => {
                    warn!("Confirmed cost proposal invalid: function-name does not reference a Clarity cost function";
                              "confirmed_proposal_id" => confirmed_proposal,
                              "cost_function" => %target_function);
                    continue;
                }
            };
            state_summary
                .cost_function_references
                .insert(target, cost_func_ref);
        } else {
```

The target contract here is `costs`, but `costs` is no longer active.  It's now `costs-2` in Stacks 2.05, and it will soon be `costs-3` in Stacks 2.1.  This needs to change in 2.1, and/or we need a way to determine the currently-active cost functions contract.

**Comment by kantai** [comment]
I'm not sure if this is a bug exactly -- that match is just used to indicate whether the target of the vote is one of Clarity's cost functions _or_ it is intended to be the cost for invoking a contract. The vote doesn't actually use that targeted contract directly, this is just directing the cost vote evaluation to either say "we're trying to change one of VM's cost functions, so use 'target_function' as a key into that enum" or "we're adding a cost short-circuit to a deployed contract, in which case use 'target_function' as the function name of that contract".
