### ISSUE TITLE
[2.1] Add a `delegate-stx` bitcoin wire format transaction

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3272]
The new features of PoX-2 in Stacks 2.1 should be great.

_However_, people using the bitcoin wire format (which isn't a small total number: it's about 10% of the liquid supply of STX), wouldn't be able to use these features without changing their wallet setup (people using 2-of-n wallets could use https://github.com/kantai/multisig-cli as long as they are willing to use a ledger device).

Adding a `delegate-stx` bitcoin wire format transaction, though, would enable them to access `pox-2` features by delegating to a normal STX address (or another multisig address), and using the delegation support there.

**Comment by friedger** [comment]
A function `delegate-stx-increase` should be added as well because stackers can only change their delegated amount when their stx are unlocked.

Alternatively, the function `delegate-stx` should be changed so that it can be increase the delegated amount while stx are locked.

**Comment by jcnelson** [comment]
Merged!

**Comment by jcnelson** [comment]
> Alternatively, the function delegate-stx should be changed so that it can be increase the delegated amount while stx are locked.

This is the approach taken in PoX 2.
