### ISSUE TITLE
BNS `name-renewal` does not emit a print event if zonefile_hash is not provided

### ISSUE THREAD

**Issue by rafaelcr** [stacks-network/stacks-blockchain#3273]
The `name-renewal` function in the BNS contract has the zonefile_hash argument set to optional so users can renew their names without having to provide this information. However, this has a side effect: the call to `update-zonefile-and-props` [has to be skipped](https://github.com/stacks-network/stacks-blockchain/blob/master/src/chainstate/stacks/boot/bns.clar#L781) (since it requires a zonefile_hash) which in turn causes the `"name-renewal"` print event **not** to be emitted with the transaction (example tx [here](https://explorer.stacks.co/txid/0xf037c8da8210e2a348bbecd3bc44901de875d3774c5fce49cb75d95f2dc2ca4d?chain=mainnet)).

This issue was causing disruptions on the Hiro API, because [names would not appear as renewed](https://github.com/hirosystems/stacks-blockchain-api/issues/1176) when they actually were. We were able to work around the issue by looking specifically for those contract calls instead, but it would be preferable if all BNS updates were reflected on contract print events.

Could there be an alternate print event emitted from that function instead?

**Comment by jcnelson** [comment]
We could just patch the Stacks node so it prints the zone file hash on a successful contract-call to `name-renewal`.

**Comment by jcnelson** [comment]
Temporarily assigning @rafaelcr to own this issue.  Please feel free to re-assign or close as you see fit.  It might be worthwhile to consider how BNSx changes the priority of this issue?

**Comment by rafaelcr** [comment]
Hi @jcnelson, sure. I think with BNSx on the way we can close this one out. I can reopen if needed in the future. Thanks.
