### ISSUE TITLE
[Clarity] add `set-element-at`

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3284]
While implementing auto-unlock in `pox-2`, @kantai discovered the need for a way to set an element in a list.  I think this is small enough we could squeeze it into the 2.1 release.

**Comment by njordhov** [comment]
What is the suggested specification of this function?

**Comment by kantai** [comment]
Something like:

```
;; returns a copy of `iterable` with the entry at index set to value
;; returns `(ok iterable')` when successful
;; returns `(err 1)` if `index` is out of bounds (i.e., `index` is not `< (len iterable)`)
;; `iterable` is a list, ascii-string, utf8-string, or buff
(set-element <iterable> <index> <value>) -> (response <iterable> uint)
```

**Comment by njordhov** [comment]
Consider avoiding the word `set` in the name of such functions, as it may wrongly suggest the sequence is mutated. Also, it would be a good idea to reserve the term for an eventual [set](https://en.wikipedia.org/wiki/Set_(abstract_data_type)) type in future version of Clarity.

> need for a way to set an element in a list

Clarity already makes it possible to change the value of an element in a list. Although it currently is cumbersome, it will be trivial to implement using the [slice](https://github.com/stacks-network/stacks-blockchain/issues/3149) function in Stacks 2.1.

**Comment by kantai** [comment]
I agree -- using `set-` is probably confusing because no mutation occurs.

Perhaps `replace-at` is a better name for this. `replace()` methods usually connote non-mutating methods in programming languages (and it avoids `set`):

See javascript (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)
also rust (https://doc.rust-lang.org/std/string/struct.String.html#method.replace)

**Comment by njordhov** [comment]
The implementation of the function [recently regressed](https://github.com/stacks-network/stacks-blockchain/pull/3296/commits/4f7070ded841182732350c47894bd7cc276cd608) to mutate the sequence as side effect. A consequence is that Clarity data structures will no longer be immutable, harming the safety and readability of Clarity contracts. This is a radical change to the language architecture that should not be taken lightly.

**Comment by jcnelson** [comment]
This has been merged :tada:
