### ISSUE TITLE
CI uses rust nightly which causes build failure in quick-xml

### ISSUE THREAD

**Issue by donpdonp** [stacks-network/stacks-blockchain#3300]
`rustup override set nightly-2022-01-14 `

https://github.com/stacks-network/stacks-blockchain/blob/master/.github/actions/bitcoin-int-tests/Dockerfile.large-genesis#L12

causes `quick-xml` crate to fail during the "Single full genesis integration test"
```
#12 77.82    Compiling quick-xml v0.25.0
#12 78.20 error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
#12 78.20   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/quick-xml-0.25.0/src/writer.rs:62:6
#12 78.20    |
```
https://github.com/stacks-network/stacks-blockchain/actions/runs/3092423899/jobs/5047532812#step:3:992

`quick-xml` compiles without issue on rust stable (1.63.0). Should this action be updated to use stable?

**Comment by jcnelson** [comment]
This should be fixed in `develop` and `next` -- the issue was that we're building on nightly to get grcov, but this is no longer necessary since it's supported in stable now.
