### ISSUE TITLE
Add base layer transaction type for API

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#3307]
Currently, the API determines that a particular tx included in a block came from the base layer by checking to see that the `raw_tx` field is set to 00. We can add another field to the transaction object to include the type of the base layer payload as an option. 

This is inspired by a change that is going to be made for subnets: https://github.com/hirosystems/stacks-subnets/issues/155

**Comment by jcnelson** [comment]
I think this is already done?  Burnchain operation events now contain a `burnchain_op` key.  Please reopen the issue if not.
