### ISSUE TITLE
Missing RPC endpoint to fetch contract constants

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#3312]
There is currently no straightforward way to retrieve a constant value defined in a smart contract with `(define-constant <name> <value>)`.

Yet, there are RPC endpoints to retrieve contract data such as data-var, map entries, interfaces, traits, readonly-fn-calls, etc:
* [`GET /v2/data_var/<addr>/<contract>/<var name>`](https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc-endpoints.md#get-v2data_varstacks-addresscontract-namevar-name)
* [`POST /v2/map_entry/<addr>/<contract>/<map name>`](https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc-endpoints.md#post-v2map_entrystacks-addresscontract-namemap-name)
* [`GET /v2/contracts/interface/<address>/<contrac>`](https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc-endpoints.md#get-v2contractsinterfacestacks-addresscontract-name)
* [`POST /v2/contracts/call-read/<address>/<contract>/<function>`](https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc-endpoints.md#post-v2contractscall-readstacks-addresscontract-namefunction-name).

For example, take the contract `SPXG42Y7WDTMZF5MPV02C3AWY1VNP9FH9C23PRXH.Marbling` which declares `(define-constant ERR-FORBIDDEN (err u403))`.

Tested approaches: 
* The [`/v2/contract/interface/...`](https://stacks-node-api.mainnet.stacks.co/v2/contracts/interface/SPXG42Y7WDTMZF5MPV02C3AWY1VNP9FH9C23PRXH/Marbling) endpoint does not include the constant values. For the given constant `ERR-FORBIDDEN` it only contains `{"name":"ERR-FORBIDDEN","type":{"response": {"ok":"none","error":"uint128"}},"access":"constant"}`
* The [`/v2/data_var/...`](https://stacks-node-api.mainnet.stacks.co/v2/data_var/SPXG42Y7WDTMZF5MPV02C3AWY1VNP9FH9C23PRXH/Marbling/ERR-FORBIDDEN) endpoint returns `Data var not found`
* It appears the only way to fetch a constant value is to define a "getter" function in the contract, then perform a `POST /v2/contracts/call-read/[Stacks Address]/[Contract Name]/[Function Name]` -- this is expensive, cumbersome, and very unintuitive especially since maps and data-vars can be fetched.

### Proposal A)

Return constants in the existing `/v2/data_var/...` endpoint. The behavior isn't that surprising, especially with some docs describing the ability to fetch constants.

### Proposal B)

Introduce a new RPC endpoint to fetch constants:
`GET /v2/constant_val/[Stacks Address]/[Contract Name]/[Constant Name]`
This would function essentially the same as the `/v2/data_var/...` endpoint but support `define-constant` values instead of `define-data-var` values.

-----

I don't have a strong preference for what approach is taken to allow this. But I do have a strong opinion that it should be possible.

Does anyone have an opinion on if this should be a new endpoint or if an existing endpoint should be expended to include this capability (most likely the `/v2/data_var/...` endpoint)?

**Comment by jcnelson** [comment]
I strongly prefer proposal B.  `data_var` queries should _specifically_ query data vars.  The distinction is important because you can create a MARF merkle proof for a data var, but not for a constant.

**Comment by friedger** [comment]
The constant is known anyway before you make a call to the contract. What is the use case for querying constants?

**Comment by jcnelson** [comment]
Not necessarily.  This is allowed, for example:

```clarity
(define-constant contract-burn-block-hash (get-block-info? burnchain-header-hash))
```

Values created with `define-constant` can be Clarity expressions.  They are evaluated when the contract is instantiated.

**Comment by jcnelson** [comment]
Going to go ahead and assign this to @kantai for the time being.  Please feel free to re-assign or close or triage as appropriate :)

**Comment by kantai** [comment]
This would be a good improvement to the RPC interface, and should be _relatively_ straightforward.

**Comment by rafaelcr** [comment]
I'd like to volunteer for this one... I've been looking for a good first issue to start getting familiar with this codebase.
