### ISSUE TITLE
Improve miner transaction selection process

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3313]
@gregorycoppola has found that when the mempool has too many transactions, the miner code will spend so long deciding what are the best transactions to pick, that it runs out of time to actually execute them. Currently, we are seeing a very full mempool and blocks that are not very full, which looks like a symptom of this situation. Let's use this issue to track ideas for quick wins.

**Comment by obycode** [comment]
Items we are discussing at Hiro:
* Currently all transactions in the mempool are read in from the database and deserialized, even if they are not valid to be considered for the block. First, we just need the nonce to know if it should be considered, only after verifying that it is a valid nonce should we deserialize the transaction.
* A `join` is required to get the fee estimate associated with a transaction; could this be slowing down the db operation? If so, we could add a `fee_rate` column in the `mempool` table

**Comment by jcnelson** [comment]
The `join` is probably slowing it down somewhat.  Last I heard he was working on denormalizing the mempool so the `join` could be avoided?

Speaking of, we should definitely remove the need to deserialize transactions that we won't be using anyway.  Just store the nonce in its own column.

**Comment by gregorycoppola** [comment]
This is the current state of the PR.

https://github.com/hirosystems/stacks-subnets/pull/157

We are seeing around 1k tiniest-possible transactions processed per second.

The algorithm currently is:
* select a very "thin" (minimal) representation of each transaction in the entire mempool (no deserialization)
* sort this list by fee rate
* for each `txid` in the sorted order:
  * check the nonce appropriateness, and `continue` if not appropriate
  * fetch and deserialize the associated `tx`
  * process this `tx`

**Comment by jcnelson** [comment]
Think you can port that over to the Stacks blockchain?

**Comment by gregorycoppola** [comment]
Yes.. it's basically the same.

The thing right now is just to re-rest without the misc hacks I put in to the draft version, and concurrently to get reviews.

**Comment by friedger** [comment]
Is fee rate the right ordering?

Same fee for stx_transfer vs a free_punk mint should prefer the stx_transfer. Is that too difficult?

**Comment by obycode** [comment]
> Just store the nonce in its own column.

Looks like the nonce is already there for us.

> Is fee rate the right ordering?

IIUC, this is a fee **rate**, so the cost of the transaction is already factored in.

**Comment by obycode** [comment]
> The thing right now is just to re-rest without the misc hacks I put in to the draft version, and concurrently to get reviews.

I am new to this part of the code, but I am happy to review and help out with any changes @gregorycoppola.

**Comment by jcnelson** [comment]
`fee_rate` is a misnomer.  It's really the tx fee.

**Comment by obycode** [comment]
It looks like the tx_fee is already in the mempool db. The `JOIN` brings in the fee estimates which I assumed was an actual rate. If not, then what is the need for that?

**Comment by jcnelson** [comment]
Oh, sorry -- I thought you were talking about `fee_rate` in the transactions or mempool table (we used to call the tx fee the fee rate, because we originally thought we were going to have txs report the _rate_ of STX expenditure).

The `fee_rate` in the `fee_estimates` table is an estimation of how much bang-for-buck the miner is going to earn by mining this tx.  The miner would want to fill blocks with high fee rates, because these transactions pay the most STX per unit of work.

What we need to do in order to eliminate the `join` is to update the schema to put the `fee_estimates` table data in the `mempool` table, e.g. alongside the transaction with the given `txid`.  It shouldn't be a very heavy lift; most of the irreducible complexity here is in migrating the old mempool schema to the new one.

**Comment by gregorycoppola** [comment]
We currently sort by fee *rates*:

https://www.hiro.so/blog/improved-fee-estimations-in-the-hiro-wallet-and-stacks-api

The biggest problem is probably the migration, as jcnelson just said.

**Comment by gregorycoppola** [comment]
The Baseline algorithm doesn't have a dwserialization problem because the
Baseline algorithm spends its time in joins.

It's only once you remove the join that you see deserialization is the
bottleneck.

**Comment by obycode** [comment]
Oh, ok. Thanks, I didn't realize that.

**Comment by obycode** [comment]
Is there a reason why there are many places in the code where we have a `MemPoolTxInfo`, then we use `tx_to_estimate.tx.txid()` instead of just `tx_to_estimate.metadata.txid`? Can I simplify all of those?

**Comment by obycode** [comment]
https://github.com/stacks-network/stacks-blockchain/pull/3314 was merged as a quick solution.

Let's keep this issue open to track the additional improvements.

**Comment by jcnelson** [comment]
Related: https://github.com/stacks-network/stacks-blockchain/issues/3320

**Comment by obycode** [comment]
Some updates from the improvements that @gregorycoppola and I have been working on.

## Branches in progress
`draft/fast-iteration--simple-limits`
The core change in this branch is that it pulls a large batch of transactions into memory from the mempool database, then builds the list of transactions to consider by iterating over that list (ordered by fee rate).

`mempool/cache-nonces`
This branch builds from the above, and adds some caching of the nonces in memory to avoid repetitively reading from the MARF to retrieve them.

`mempool/cache-nonces-and-loop`
This branch builds from the above, and changes the behavior between transactions to restart at the beginning of the loop each time. This ensures that the higher fee-rate transactions whose nonces may have been updated by the last transaction get picked before lower fee-rate transactions later in the list. This matches the algorithm in master, but sacrifices some speed for this behavior.

## Benchmarking Experiments

This benchmarking is done using a chainstate [snapshot](https://storage.googleapis.com/blockstack-publish/mainnet/blockchain/mainnet-blockchain-2.05.0.3.0-20221001.tar.gz) from 10/1 on my M1 MacBook Pro. I am running:
```
 stacks-inspect try-mine stacks-node/data/ 10 30000
```
Values reported are an average of 10 consecutive runs.

| Branch | Commit | Num Tx | %-Full | Time Spent |
| --- | --- | --- | --- | --- |
| master | 378fc1b80e161ce1b82cc98b3802565222100816 | 124 | 4.97% | 31002.5ms |
|  draft/fast-iteration--simple-limits | 77f9a7918fcc372a316060c18f0800e235082e06 | 1034 | 99.97% | 12587.0ms |
| mempool/cache-nonces-and-loop | 67a613c2cdf7718479359834e860b8878ecc4ec5 | 1097 | 100% | 13625.7ms |
| mempool/cache-nonces | 087daaeea5907a7d4444a6269700bf34e29f3076 | 1034 | 99.97% | 11426.5ms |

## Testing

* `core::tests::mempool_walk_over_fork`: fails due to the structure of the test; It is relying on behavior from the implementation in master -- specifically the `last_known_*_nonce` fields in the mempool database, which are unused with these changes
* `tests::neon_integrations::microblock_integration_test`: fails in CI but is passing locally; I have seen the same behavior in other PRs
* `tests::neon_integrations::size_overflow_unconfirmed_microblocks_integration_test`: fails in CI but is passing locally
* `tests::neon_integrations::block_large_tx_integration_test`: fails in CI but is passing locally

## Remaining work

* [ ] Implement a paging/iterator to allow for the case when a block requires transactions past the limit initially pulled into memory
* [ ] Discuss tradeoff described above with looping behavior; a more complicated implementation (e.g. ready-list) could solve the ordering problem and maintain performance, but might not be worth the additional complexity

**Comment by obycode** [comment]
This can be closed now that #3337 is merged and will be released with 2.05.0.5.0. We will track additional improvements in the [Faster L1 Working Group](https://github.com/stacks-network/stacks/discussions/468). If this issue was interesting to you, come join us.
