### ISSUE TITLE
More information from analysis errors

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3328]
When attempting to deploy a contract, if the analysis fails, there is no information provided about the error in the transaction result, just a result of `(err none)`. Ex. [Transaction in explorer](https://explorer.stacks.co/txid/0xce6e56d0392c64acdd3240b7135b04268492d2eff5c2b913d3ce272ff5056425?chain=testnet]), [API retrieving transaction](https://stacks-node-api.testnet.stacks.co/extended/v1/tx/0xce6e56d0392c64acdd3240b7135b04268492d2eff5c2b913d3ce272ff5056425)

It would be nice to get more information about the error.

This is related to #3154

**Comment by jcnelson** [comment]
We could store the string representation of the error in the blacklisted txids table in the mempool, and serve that out of /v2/transactions.

**Comment by jcnelson** [comment]
Temporarily assigning to @obycode, but it sounds like this should be delegated to the explorer team?  Please re-assign to a more appropriate person if so :)

**Comment by obycode** [comment]
This problem is related to #3587 that @kantai just fixed. Is there any reason why the analysis error is not passed in the `vm_error` field of the receipt here? 

https://github.com/stacks-network/stacks-blockchain/blob/0910326be8b767cd47b7ab6b4918be4242f9f68a/src/chainstate/stacks/db/transactions.rs#L183-L199

**Comment by kantai** [comment]
I don't think there's any reason not to pass that error into the receipt.

The `vm_error` field was added with the 2.1 change to `CheckError` handling (see https://github.com/stacks-network/stacks-blockchain/commit/b712a1d2959fecde6f42605951d2f4ed3b2aeeda), so I think the other receipt types just weren't updated to include more information.

**Comment by obycode** [comment]
Oh, that explains it. Thanks. I was curious why that wasn't there already. I'll open a PR.

**Comment by obycode** [comment]
Do we think this should contain a more machine-readable format, like `UnexpectedToken(Rparen)`, or the more user-friendly format, like `Tried to close list which isn't open.`, or even better, when a position is available: `:2:9: invalid variable definition`.
