### ISSUE TITLE
Make "first attempt" timeout to be 15s, to fill the first attempt block

### ISSUE THREAD

**Issue by gregorycoppola** [stacks-network/stacks-blockchain#3332]
**Is your feature request related to a problem? Please describe.**
Currently, the default "first attempt" time for the miner is 5 seconds:
* https://github.com/stacks-network/stacks-blockchain/blob/378fc1b80e161ce1b82cc98b3802565222100816/testnet/stacks-node/src/config.rs#L1523

This was done so that miners could get *some* bid in before attempting a block. But, that was when it was thought to take up to 180 seconds to make a block.

The problem is that if this default miner never gets their second bid through, we now have an empty block:
![image](https://user-images.githubusercontent.com/60008382/194721296-deba112b-30a6-457e-b601-5bb937df26bb.png)

Now that block time is around 10-12 seconds (https://github.com/stacks-network/stacks-blockchain/issues/3313#issuecomment-1269264281), we can make the timeout to be 15 seconds by default.

This way, by default:
* the miner's first block attempt would be full
* they aren't meanginfully more likely to miss the Bitcoin block time (10-5=5seconds different, on a 10minute average block time)

**Describe the solution you'd like**
Change the default to 15s, with the block likely done in 10-12s, without even hitting the timeout.

**Describe alternatives you've considered**
You could change the toml files instead, but:
* if users have their own toml files, we can't change those
* if users are going with out of the box defaults, they will, afaiu, pick up these

Caveats:
* some miners might not want the new behavior
  * but, users using the defaults presumably want the improved defaults

**Additional context**
https://github.com/stacks-network/stacks-blockchain/issues/3313#issuecomment-1269264281

**Comment by jcnelson** [comment]
Needs more data.

**Comment by muneeb-ali** [comment]
@gregorycoppola I'm assuming this is relevant for any discussions on block size etc?

**Comment by gregorycoppola** [comment]
@jcnelson Which data are we looking for? Do we just need to run a mock miner and see what the distribution of block times is?

@muneeb-ali I'm not sure if I totally understand the question. But, the "first attempt time" is a value that isn't part of consensus. The miner makes multiple "attempts" at filling a block. Historically, the "first attempt" has always been almost empty, because the budget was 5s, and 5s was very small compared to the time needed to fill a block. A miner can unilaterally change this, or override it, as part of their own mining strategy. For those miners who use the "default", this new default would mean the "first attempt" is full. The "first attempt time" is related to the block limit, because the faster block-filling time impacts both.

**Comment by jcnelson** [comment]
Given that the miner is now much, much faster at producing blocks, I think we can close this.
