### ISSUE TITLE
Docs: link to whitepaper outdated

### ISSUE THREAD

**Issue by eleijonmarck** [stacks-network/stacks-blockchain#3362]
**why/what**
[Proof of X] link is taking me to : https://uploads-ssl.webflow.com/5ff21113877dd72b9f913b35/6154471366c15dae30133499_pox.pdf

However there seems to be a more updated version of the whitepaper from May - https://assets.website-files.com/5fcf9ac604d37418aa70a5ab/60072dbb32d416d6b3806935_5f1596b12bcc0800f3dcadcd_pox.pdf

whats needed:
- update the link on line [5](https://github.com/stacks-network/stacks-blockchain/blob/master/README.md?plain=1#L5) in readme https://blockstack.org/pox.pdf to point to the updated version

**Comment by CharlieC3** [comment]
Updated! https://blockstack.org/pox.pdf will now redirect to the whitepaper from May.
