### ISSUE TITLE
[Clarity] Implement remaining common bitwise operators

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/stacks-blockchain#3377]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would make it much easier to work with bits if the common bitwise operations were available as built-in functions.

**Describe the solution you'd like**
We have `xor` today, would be nice to have bitwise `and`, `or`, `not`, `left shift` and `right shift` functions as well.  I personally don't need all of them, but if implementing one or two it would feel relevant to make sure that at least the most common bitwise functions are implemented.

**Describe alternatives you've considered**
Currently using good-old-fashioned math combined with list constants, however this is rather cumbersome.

**Additional context**
Having the ability to easily store information in bitwise flags would help to reduce the amount of space needed to store e.g. role-principal mappings (have seen many examples with each role-principal mapping being stored in separate maps, for example).  Could also be useful in certain parsing situations.

**Comment by jcnelson** [comment]
You can implement them today with the existing operations.

**Comment by cylewitruk** [comment]
I had a look at the existing code for `xor` and it looks fairly straightforward.  I'd be happy to take a stab at implementing these if it would be welcomed.

**Comment by jcnelson** [comment]
Sure, but please see my other comment on this regarding expectations we place on such PRs: https://github.com/stacks-network/stacks-blockchain/issues/3378#issuecomment-1303520260

**Comment by cylewitruk** [comment]
If someone feels like throwing an eye on the above feature branch before I PR it that would be much appreciated.  Seems to work anyway and all tests pass (that passed before I dug my fingers into it) 🤷 Branched from `next` since that's what the guidelines said to do for consensus-breaking changes.

**Comment by jcnelson** [comment]
This is now merged!  Thank you for your PR @cylewitruk.  The technical CAB has signed off on the implementation, so we're good to go.

**Comment by cylewitruk** [comment]
> This is now merged! Thank you for your PR @cylewitruk. The technical CAB has signed off on the implementation, so we're good to go.

Awesome! Thanks a lot for the help, reviews and guidance during this "crash course" 😅
