### ISSUE TITLE
[Clarity] Productivity improvement, `map-exists`

### ISSUE THREAD

**Issue by cylewitruk** [stacks-network/stacks-blockchain#3378]
**Is your feature request related to a problem? Please describe.**
No, simply a productivity and LoC improvement.

**Describe the solution you'd like**
Someones we simply want to check if a key exists in a map.  It would be nice to have a `map-exists` method which returns true/false if the key exists or not.  I'm thinking a signature similar to `map-delete`:

**input:** `MapName`, `tuple`
**output:** `bool`
**signature:** `(map-exists map-name key-tuple)`

**Describe alternatives you've considered**
Completely possible using the current syntax, would just save on some LoC.

**Additional context**
None

**Comment by jcnelson** [comment]
You can implement this today with the existing operations.

**Comment by cylewitruk** [comment]
Fully possible today, yes, but each function must be written map-specific since `MapName` is not a valid type in Clarity, and there is no `any` type to handle the key type.  So, at least for me, a build-in function would save a few lines of code (and I assume therefore both cost of storage and cost of execution).

**Comment by cylewitruk** [comment]
I'd be happy to take a stab at implementing this if it would be welcomed.

**Comment by njordhov** [comment]
For reference and experimentation, here is a ClarityTools generic function [implementation of map-exists](https://shrtco.de/ySyLcR). Generate Clarity from the Toolbox menu.

**Comment by cylewitruk** [comment]
Well that's cool @njordhov, I didn't actually know that clarity tools had that generic syntax available :) Learn something every day...

Point still being that a separate function must be defined per-map, and several additional operations used to get to the answer for a very simple operation. The internals could be much simpler, making use of the internal store's `[has_entry](https://github.com/stacks-network/stacks-blockchain/blob/26bfd5fcdc1f25106288f18ced05290b569f6abb/clarity/src/vm/database/clarity_store.rs#L65)` function and avoiding reading the map's data (and associated costs).  Most languages have built-in functions to determine if a key exists in a given map/dictionary.

**Comment by jcnelson** [comment]
> @cylewitruk I'd be happy to take a stab at implementing this if it would be welcomed.

Sure, PRs are always welcome :)  But to set expectations:

* Changes to the Clarity language are breaking changes, so there'd be no adoption until the next hard fork (which would be sometime next year)

* Because new Clarity language features are part of the consensus-critical code, there's a very high bar for such PRs.

**Comment by njordhov** [comment]
> Point still being that a separate function must be defined per-map, and several additional operations used to get to the answer for a very simple operation.

To follow up on the warning by @jcnelson about the "very high bar for such PRs", you may consider to start by instead submitting it as a [SIP](https://github.com/stacksgov/sips).

**Comment by jcnelson** [comment]
I think this issue should be moved to https://github.com/clarity-lang/reference.  Please re-open there if there is still interest.

**Comment by njordhov** [comment]
[clarity-lang/reference](https://github.com/clarity-lang/reference/issues) is unfortunately another `/dev/null` by now.

**Comment by jcnelson** [comment]
Nothing stops either of you from sending a PR to implement the requested feature.
