### ISSUE TITLE
[Stacks 2.1] `ast::build_ast_with_rules()` should always require `ASTRules::PrecheckSize` in 2.1

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3384]
There's no need to support `ASTRules::Typical` after the 2.1 upgrade.  It's already no longer supported in 2.05 via a soft fork.

**Comment by obycode** [comment]
Would it be correct that we can actually delete all of the code related to handling the different rulesets? After the soft-fork, I think all of this related code can be deleted, simplifying things.

**Comment by jcnelson** [comment]
Yup!

**Comment by jcnelson** [comment]
Ugh fat-fingered

**Comment by jcnelson** [comment]
Merged!
