### ISSUE TITLE
Miner accidentally stop syncing when winning a block which is not broadcasted then

### ISSUE THREAD

**Issue by MaksimalistT** [stacks-network/stacks-blockchain#3400]
**Describe the bug**
Miner accidentally stop syncing when winning a block which is not broadcasted then
node stalled
no commits
only restart helps

**Steps To Reproduce**
don't know

**Environment (please complete the following information):**
 - OS: Amazon Linux
 - Rust version: 1.65.0
 - Stacks node: 2.05.0.5.1

**Additional context**
[debug log](https://watcher-data.s3.amazonaws.com/freezed_miner_debug.log.gz)

p.s. is it possible to broadcast the block to be accepted by the network?

**Comment by wileyj** [comment]
Intereseting....can you share more about the setup you're running?
are you in the discord server/telegram ? happy to chat there

**Comment by wileyj** [comment]
you can also reach out via email to me directly to discuss since some of your setup you may not  want to disclose here: `wileyj` `@` `stacks.org` for reference, i'm part of the Stacks Foundation and issues like this are what i specialize in.

**Comment by MaksimalistT** [comment]
Hi, @wileyj 
can't find you on a discord
i use standard setup, issue started to appear since last release, and other miners experience it too, but not yet reported for some reason.
did you find attached logs?

**Comment by wileyj** [comment]
i'm on the stacks discord as `jw#4439`

**Comment by wileyj** [comment]
> Hi, @wileyj can't find you on a discord i use standard setup, issue started to appear since last release, and other miners experience it too, but not yet reported for some reason. did you find attached logs?

I did look over the logs, and there's a few things that i noticed in there i'd rather not discuss publicly since it pertains to your specific mining setup.

**Comment by MaksimalistT** [comment]
@jcnelson is there a stable branch with the fix to deploy on mainnet?

**Comment by MaksimalistT** [comment]
there is another problem, miner can skip several blocks due to 
Relayer: Failure mining anchored block: Bad nonce: origin account [miner_address] nonce of tx [txid] is 109 (expected 110)

**Comment by jcnelson** [comment]
This should be fixed in `master` now.

**Comment by jcnelson** [comment]
Going to close this due to inactivity.  I also replied on #3420.  If the problem still persists, please reopen :)
