### ISSUE TITLE
Update CI actions for Node 16

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3403]
I noticed that we are getting a bunch of warnings from our CI actions because they are using Node.js 12, which is deprecated. They seem to be mostly coming from third party tools where we just need to use the latest version, e.g. `actions/checkout@v2` --> `actions/checkout@v3`.

**Comment by obycode** [comment]
Will be fixed in #3199

**Comment by jcnelson** [comment]
Temporarily assigning to @wileyj so it has an owner.  This can close once #3199 merges.

**Comment by wileyj** [comment]
👍 already restarted work on that PR (i may break out issues like this separately to keep the PR manageable)

**Comment by wileyj** [comment]
this was done in #3199
