### ISSUE TITLE
[Stacks 2.1] Miner error for epoch `start_height` and `pox_2_activation` config values

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#3407]
_Initial context for this issue in the comments from another issue: https://github.com/stacks-network/stacks-blockchain/issues/3261#issuecomment-1310606024_

A regtest+krypton miner will error and fail to mine with certain epoch `start_height` and `pox_2_activation` (i.e. `v1_unlock_height`) config.toml values.

Once the `pox_2_activation` height is reached, the error `Failure fetching recipient set: ChainstateError(ClarityError(Interpreter(Unchecked(NoSuchContract("ST000000000000000000002AMW42H.pox-2")))))` is logged in an indefinite loop. 

Some config values _do_ work, but approximately 3/4ths of different combinations of these config values will trigger this error.

See the [full debug log output here](https://gist.githubusercontent.com/zone117x/ac7112451dbaa0faf7ca0b6e41b444b9/raw/d4a72358e89494c3342af2359cb7a590961005e5/output_log.txt) from when this error happens.

Go to the end of the log to see where the miner loops with the error:
```
ERRO [1668778959.365802] [testnet/stacks-node/src/neon_node.rs:1674] [miner-block-http://0.0.0.0:20443] Relayer: Failure fetching recipient set: ChainstateError(ClarityError(Interpreter(Unchecked(NoSuchContract("ST000000000000000000002AMW42H.pox-2")))))
```

See [here for the `config.toml` file](https://gist.github.com/zone117x/ac7112451dbaa0faf7ca0b6e41b444b9#file-config-toml) used, and [here for the `btc-mining-script.sh` script](https://gist.github.com/zone117x/ac7112451dbaa0faf7ca0b6e41b444b9#file-btc-mining-script-sh) used.

I've also added pushed a docker setup so anyone can easily reproduce this locally, see https://github.com/zone117x/stacks-regtest-env/pull/16

**Comment by zone117x** [comment]
@jcnelson let me know if there's anything else I can provide to help with this. I can easily test different config values, and/or a potential fix branch if you push any.

**Comment by jcnelson** [comment]
Hey @zone117x , try this PR: https://github.com/stacks-network/stacks-blockchain/pull/3409

**Comment by jcnelson** [comment]
We've added test coverage for appropriate values for `start_height` and `pox_2_activation`, and have done dress rehearsals.  Going to go ahead and close this.
