### ISSUE TITLE
[Stacks 2.1] /v2/pox reporting incorrect .contract_id

### ISSUE THREAD

**Issue by janniks** [stacks-network/stacks-blockchain#3422]
**UPDATE:**

https://github.com/stacks-network/stacks-blockchain/pull/3451 seems to fix the issue, but due to how the pox-rpc response is set up, the resulting `.contract_id` switch to `pox-2` is delayed by a cycle (rather than just by one block). This happens because the `active_pox_contract()` method is called using the reward cycle start heights and not the exact current burn height.

https://github.com/stacks-network/stacks-blockchain/blob/e21347232f9ab2b4417a33476c8eb0131756f1a0/src/net/rpc.rs#L426-L427

---

**PREVIOUS BEHAVIOR:**

> This bug was encountered during the development of https://github.com/hirosystems/stacks-blockchain-api/pull/1454

**Describe the bug**
It would seem that the reported /v2/pox contract_id is wrong in at least one case.

The switch to .pox-2 as "active" _(being the .contract_id in /v2/pox)_ happens 1 block early (on block `v1_unlock_height`).

**Expected behavior**
According to SIP-015 and related discussions, it is my understanding that it should switch on `v1_unlock_height + 1` and NOT `v1_unlock_height` itself.

> Since the switch happens "early", it doesn't feel like a race condition — so, I don't know what else could cause this...

---

**Steps To Reproduce / Additional Context**
[Here is an API-test](https://github.com/hirosystems/stacks-blockchain-api/blob/8fdc9091d339ab1bc7a065f0f7175ea1eb369649/src/tests-2.1-transition/pox-transition.ts#L334-L342) for reproduction or as pseudo-code to follow exactly what's going on.

```ts
// We are still in Period 2a
expect(poxInfo.current_burnchain_block_height).toBeLessThan(poxInfo.contract_versions![1].activation_burnchain_block_height + 1);

expect(poxInfo.contract_id).toBe('ST000000000000000000002AMW42H.pox'); // FAILS
expect(poxInfo.contract_id).toBe(poxInfo.contract_versions![0].contract_id); // FAILS
```

> In the API-repo these `expects` are commented out to pass the tests for now...

**Comment by janniks** [comment]
https://github.com/stacks-network/stacks-blockchain/pull/3451 seems to fix the issue, but due to how the pox-rpc response is set up, the resulting `.contract_id` switch to `pox-2` is delayed by a cycle (rather than just by one block). This happens because the `active_pox_contract()` method is called using the reward cycle start heights and not the exact current burn height.

https://github.com/stacks-network/stacks-blockchain/blob/e21347232f9ab2b4417a33476c8eb0131756f1a0/src/net/rpc.rs#L426-L427

---

There is some related weirdness (maybe bugs or unintentional behavior) related to this. The things we've been observing are covered in this graphic:

<img width="1343" alt="pox-rpc (1)" src="https://user-images.githubusercontent.com/6362150/211611702-4d7094aa-d34d-4dc1-99cd-fa80ab39f2a5.png">


> _The graphic shows repeated calls to the `/v2/pox` endpoint. Each json-response one call (refresh). The calls are in order from left-to-right. The weird/wrong information is in `.current_cycle { }` and `.next_cycle { }`_

**Comment by donpdonp** [comment]
Thanks for catching that. The current contract_id is setup to report the contract in effect at the start of the reward cycle - I assume previuos epoch transitions happened on reward cycle boundaries. Its a 1-liner to have contract_id give the contract name for the current block instead of the current reward cycle, but I'm unsure of whether or not that change would invalidate other assumptions. 

Here is the 1-liner

```
diff --git a/src/net/rpc.rs b/src/net/rpc.rs
index efa7891c6..b1a3601b8 100644
--- a/src/net/rpc.rs
+++ b/src/net/rpc.rs
@@ -423,6 +423,7 @@ impl RPCPoxInfoData {
                 net_error::ChainstateError("Burn block height overflowed i64".into())
             })?;
 
+        let cur_block_pox_contract = pox_consts.active_pox_contract(burnchain_tip.block_height);
         let cur_cycle_pox_contract =
             pox_consts.active_pox_contract(burnchain.reward_cycle_to_block_height(reward_cycle_id));
         let next_cycle_pox_contract = pox_consts
@@ -475,7 +476,7 @@ impl RPCPoxInfoData {
         let cur_cycle_pox_active = sortdb.is_pox_active(burnchain, &burnchain_tip)?;
 
         Ok(RPCPoxInfoData {
-            contract_id: boot_code_id(cur_cycle_pox_contract, chainstate.mainnet).to_string(),
+            contract_id: boot_code_id(cur_block_pox_contract, chainstate.mainnet).to_string(),
             pox_activation_threshold_ustx,
             first_burnchain_block_height,
             current_burnchain_block_height: burnchain_tip.block_height,
```
I'm having to dig deep to figure out how a test case might cover this so I wanted to post a partial progress report.

**Comment by donpdonp** [comment]
that two-line change has been committed to branch [feat/cur_block_pox_contract](https://github.com/stacks-network/stacks-blockchain/tree/feat/cur_block_pox_contract) while its still not covered by a specific test, I thought having a branch might help run the api test suite against it.

**Comment by donpdonp** [comment]
unit test for this change is in https://github.com/stacks-network/stacks-blockchain/pull/3546

**Comment by donpdonp** [comment]
issue fixed with https://github.com/stacks-network/stacks-blockchain/pull/3548 and merged into develop branch.
@janniks does this fix the failing API test?

**Comment by jcnelson** [comment]
The PRs that fix this are merged.  @janniks please re-open if the issue persists.  Thanks!
