### ISSUE TITLE
Remove From<&'_ str> implementation for `guarded_string` macro

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3431]
`From` is intended for perfect/infallible conversions. The `From<&'_ str>` implementation in the `guarded_string` macro is not as it may panic.

**Why is this a problem?**
Implementing `From` also implicitly implements `TryFrom` ([link](https://doc.rust-lang.org/src/core/convert/mod.rs.html#600)). This gives us an implicit `TryFrom<&'_ str`> implementation which panics on errors that is easy to accidentally call when intending to call `TryFrom<String>`.

We already have multiple instances of this in the code, such as in `clarity/./src/vm/database/clarity_db.rs:715`:
```
ClarityName::try_from("reporter").expect("BUG: valid string representation")
```

another example is in `src/net/mod.rs:2662`
```
let smart_contract =
  TransactionPayload::SmartContract(TransactionSmartContract {
    name: ContractName::try_from(conf.test_name.as_str())
    .expect("FATAL: invalid boot-code contract name"),
```

The `expect()` statements in these examples are unreachable, even though it is evident that this was not the intention of the developer.

**Proposal**
Remove the `From<&'_ str>` implementation altogether. It provides more risks than value. The few legitimate use-cases can easily be refactored to `try_from(...).unwrap()` or `try_into(...).unwrap()`.

**Comment by netrome** [comment]
> IIRC the reason `guarded_string` uses `From` is because there are lots of cases in the code where we use `.into()` to convert a `&str` literal into a `guarded_string`, or to convert a stored but already-checked string back into a `guarded_string`. _These cases should panic if they fail_, because their failure indicates database corruption.

I see. In those cases I'd argue an `.try_into().unwrap()` conveys the intention better to the reader. If this is too verbose, we could add a shorthand for this that avoids the risks of the current implementation. The ideal solution for string literals would of course be to enforce the formatting rules at compile time.

**Comment by jcnelson** [comment]
Temporarily assigning to @netrome for now.  Please feel free to reassign.  If you don't think you'll get to this for some time, it might be better to just copy this issue text to a comment in #3412 and close it out here.

**Comment by netrome** [comment]
Great. I'm happy to implement this. When we last discussed this you wanted to await Aaron to sanity check this idea before jumping to any implementation.

@kantai do you have any opinions on this? My intention is basically to remove a panicking `From<&'_ str>` implementation, and replace all calls to `.into()` with `.try_into().unwrap()` to make the panic more explicit, and avoid nasty surprises for future developers.

The history behind this issue is that I was spending way to long time to find the cause of a panic hidden behind a `.try_from(a_string).expect("Some unreachable message")`, because I quickly ruled out the panicking line as the cause of the panic due to the absent expect message.

**Comment by kantai** [comment]
Yeah -- getting rid of this seems like a good idea to me.

**Comment by netrome** [comment]
> Yeah -- getting rid of this seems like a good idea to me.

Great, thanks! I'll prepare a PR for this when I find the time.

**Comment by netrome** [comment]
I won't have the time to fix this. I'll close the ticket for now, and anyone can re-open it when you're interested in addressing this issue.
