### ISSUE TITLE
Add getter for pox2 stacking amount

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-blockchain#3436]
**Is your feature request related to a problem? Please describe.**
As a smart contract for stacking pool payouts I want to know how many stx a principal has stacked for a given reward cycle.

**Describe the solution you'd like**
Add function `get-stacker-info-by-cycle` in pox-2 contract that returns the amount stacked in a given cycle.

**Describe alternatives you've considered**
I don't see any alternative solution today.

**Additional context**
It was available in pox (v1) as part of the stacker-info.

**Comment by jcnelson** [comment]
> As a smart contract for stacking pool payouts I want to know how many stx a principal has stacked for a given reward cycle.

Can you elaborate more?  You can use the new `stx-account` Clarity function to get a principal's locked and unlocked balances, and `get-stacker-info` is still present in `pox-2`.  Is there something more?

**Comment by friedger** [comment]
`stx-account` was the missing information. Together with at-block it should work.
