### ISSUE TITLE
stacks-node error while syncing burnchain headers

### ISSUE THREAD

**Issue by jiga** [stacks-network/stacks-blockchain#3442]
**Describe the bug**
stacks node is stuck in indefinite loop while syncing burnchain headers and there is an error verifying previous block hash.

**Steps To Reproduce**
start a follower node with empty data to do a full sync of chain

**Expected behavior**
no sync error 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Rust version
 - Version of the appropriate binary / software package : stacks-node 2.05.0.6.0 (aarch64) from docker image (ceramicwhite/stacks-blockchain)

**Additional context**
```
DEBG [1670995992.791286] [src/burnchains/burnchain.rs:596] [main] Fetch initial headers
DEBG [1670995992.791365] [src/burnchains/bitcoin/indexer.rs:368] [main] Sync all headers starting at block 410000
DEBG [1670995992.803491] [src/burnchains/bitcoin/spv.rs:737] [main] Initialized block headers at /app/stacks-blockchain/data/mainnet/headers.sqlite
DEBG [1670995992.842246] [src/burnchains/bitcoin/indexer.rs:274] [main] (Re)establish peer connection
DEBG [1670995992.843989] [src/burnchains/bitcoin/network.rs:158] [main] Begin peer handshake to 10.21.21.8:8333
DEBG [1670995992.844042] [src/burnchains/bitcoin/network.rs:258] [main] Send version (nonce=4972053372756252336) to 10.21.21.8:8333
DEBG [1670995992.858150] [src/burnchains/bitcoin/network.rs:269] [main] Handle version -- remote peer blockchain height is 767338
DEBG [1670995992.858281] [src/burnchains/bitcoin/network.rs:287] [main] Send verack
DEBG [1670995992.860153] [src/burnchains/bitcoin/network.rs:296] [main] Handle verack
DEBG [1670995992.860204] [src/burnchains/bitcoin/network.rs:169] [main] Established connection to 10.21.21.8:8333, who has 767338 blocks
DEBG [1670995992.860226] [src/burnchains/bitcoin/spv.rs:1152] [main] Get headers 410000-767338 to /app/stacks-blockchain/data/mainnet/headers.sqlite
DEBG [1670995992.860446] [src/burnchains/bitcoin/network.rs:346] [main] Send GetHeaders 0000000000000000060d7ea100ecb75c0a4dc482d05ff19ddaa8046b4b80a458 for 2000 headers to 10.21.21.8:8333
DEBG [1670995992.865229] [src/burnchains/bitcoin/network.rs:310] [main] Handle ping 2197584937521544083
DEBG [1670995992.865271] [src/burnchains/bitcoin/network.rs:313] [main] Send pong 2197584937521544083
DEBG [1670995992.983447] [src/burnchains/bitcoin/spv.rs:882] [main] Insert 2000 headers to /app/stacks-blockchain/data/mainnet/headers.sqlite after block 410000
WARN [1670995992.983667] [src/burnchains/bitcoin/spv.rs:507] [main] Bad SPV header for block 410199: header prev_blockhash 0000000000000000046781e9d176317f78a8a27ba08118dc667ee2c33c57d567 != prev_header hash c08f4be557984a90a9d0d69453ed445859cb568d6b8a529de7d667c7c0398607
ERRO [1670995992.983677] [src/burnchains/bitcoin/spv.rs:890] [main] Received invalid headers: NoncontiguousHeader
ERRO [1670995992.983725] [src/burnchains/bitcoin/spv.rs:767] [main] Failed to insert block headers: NoncontiguousHeader
WARN [1670995992.983731] [src/burnchains/bitcoin/indexer.rs:338] [main] Unhandled error NoncontiguousHeader
ERRO [1670995992.999281] [src/burnchains/burnchain.rs:598] [main] Failed to sync initial headers
ERRO [1670995992.999319] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:474] [main] Unable to sync with burnchain: Non-contiguous header
```
If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

**Comment by wileyj** [comment]
config and exec would be helpful here. 
additionally, is the btc node `10.21.21.8` responding to connections? what is the current tip height?

the only time i've seen this is when there was a corruption of the chainstate (can be caused by several things - in my case i force killed during the iniitial block header sync and restarted)

**Comment by jiga** [comment]
config is same as used for umbrel app from ceramicwhite

I verified that btc node was responding for connections and also tried to fetch the failing block height to manually check on the block_hash, it it looked good there.  

I did try clearing working_dir and let stacks node sync again but it failed again. Unfortunately this time it was bitcoind not able to validate some block header and got stuck there. So I guess the corruption may have started at bitcoin chain.

I see one possible improvement for Stacks out of this could be to connect to multiple bitcoin peers for syncing burnchain, so that it can recover instead of failing. makes sense?

**Comment by wileyj** [comment]
Yea, if it bitcoin itself has bad data for some reason that could definitely have adverse downstream effects. 
There is already an issue for the idea of using primary/secondary burnchains - it's something I thought would be a good idea a while back myself. it hasn't been a priority, but once 2.1 is released maybe it can finally be worked on.
