### ISSUE TITLE
[sBTC] Introduce Epoch 3.0

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3482]
Some preliminary exploration of necessary code paths have been performed in PR #3475.

**Comment by jcnelson** [comment]
Temporarily assigning to @netrome for now.  Please feel free to reassign or close.  If we go with the [mini sBTC](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit#) approach, then this might not need to be done for some time and we can close it for now.

**Comment by netrome** [comment]
Sure. Since this is on the sBTC roadmap, and not part of mini sBTC I'll close this issue. We can create actionable items for Epoch 3.0 when we're done with mini sBTC.
