### ISSUE TITLE
Make `stacks_common::types::Address` require FromStr

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3483]
The trait currently looks like this:
```
pub trait Address: Clone + fmt::Debug + fmt::Display {
    fn to_bytes(&self) -> Vec<u8>;
    fn from_string(from: &str) -> Option<Self>
    where
        Self: Sized;
    fn is_burn(&self) -> bool;
}
```

I suggest changing the signature to
```
pub trait Address: Clone + fmt::Debug + fmt::Display + std::str::FromStr{
    fn to_bytes(&self) -> Vec<u8>;
    fn is_burn(&self) -> bool;
}
```

This will lead to the following improvements:
1. The trait is smaller and cleaner
2. Improved error handling as `FromStr` requires a result to be returned instead of an Option
3. Proper naming. `from_string` does not take a `String` as input, but a `&str`

**Comment by jcnelson** [comment]
Temporarily assigning to @netrome for now.  Please feel free to re-assign, or even close it and note it in #3412.

**Comment by netrome** [comment]
I'll make a note in #3412.
