### ISSUE TITLE
Refactor: Remove unneccessary generics from `FromRow` and `FromColumn` traits

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3513]
The name of these traits suggest their `from` method should return `Self` and not the generic `T` parameter which could be any type. This should not be possible. All current implementations of these traits are compatible with this restriction.

Motivation:
_Why would anyone ever want to implement FromRow\<T\> for type S if S!=T?_

To make it even more idiomatic, we could make the traits empty and simply require `TryFrom<Row>`, and add a blanket implementation for all types implementing `TryFrom<Row>`.

**Comment by jcnelson** [comment]
Temporarily assigning to @netrome for now.  Feel free to close it and move it to https://github.com/stacks-network/stacks-blockchain/discussions/3412 if you don't think you'll get to it anytime soon.

**Comment by netrome** [comment]
Added to #3412 I'll tackle this when I find the time, but it's a low prio.

**Comment by netrome** [comment]
I won't have time to tackle this.
