### ISSUE TITLE
[sBTC] Validate peg out request operations

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3514]
Once Epoch 3.0 and the updated .pox contract for sBTC is in place, we should ensure peg out requests have valid signatures and that the receiver holds the equivalent amount of sBTC on the stacks blockchain.

**Comment by jcnelson** [comment]
Temporarily assigning this to @netrome so it has an owner.

If we take the approach of building out [mini sBTC](https://docs.google.com/document/d/1R33gZupJg0KsY-vRZYbVFwTHRmq2BCIvyPIVeY0JyGM/edit?usp=sharing) first, then this validation would happen entirely outside the blockchain as part of the `sbtc-signer` daemon.

**Comment by netrome** [comment]
Yeah, we should handle this issue the same way we decide to handle https://github.com/stacks-network/stacks-blockchain/issues/3494
