### ISSUE TITLE
[sBTC] Devnet stacks-coordinator CLI

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3518]
The stacks coordinator is a part of the [devnet sBTC delivery](https://docs.google.com/document/d/1u2bwsDkGCPgGe93XnKncC3mOxLYGjZPcBGGs06M7shU/). It's a standalone CLI which sends messages to a relay server in order to

- Initiate distributed key generation between signers
- Ask signers to sign a single message
- Query the signers for their aggregate public key

The coordinator keeps track of the aggregate public key that the signers generate after a successful key generation round.

## Example flow: Distributed key generation
```mermaid
sequenceDiagram
    participant C as Coordinator
    participant R as Relay
    participant S as Signer
    C->>+R: DKG_BEGIN
    R->>S: DKG_BEGIN
    S-->R: DKG_PUBLIC_SHARES
    S-->R: DKG_PRIVATE_SHARES
    S->>R: DKG_END
    R->>-C: DKG_END
```

## Example flow: Sign message
```mermaid
sequenceDiagram
    participant C as Coordinator
    participant R as Relay
    participant S as Signer
    C->>+R: NONCE_REQUEST
    R->>S: NONCE_REQUEST
    S->>R: NONCE_RESPONSE
    R->>-C: NONCE_RESPONSE (xT)
    C->>+R: SIGN_SHARE_REQUEST
    R->>S: SIGN_SHARE_REQUEST
    S->>R: SIGN_SHARE_RESPONSE
    R->>-C: SIGN_SHARE_RESPONSE (xT)
```

## Example flow: Query aggregate public key
```mermaid
sequenceDiagram
    participant C as Coordinator
    participant R as Relay
    participant S as Signer
    C->>+R: DKG_QUERY
    R->>S: DKG_QUERY
    S->>R: DKG_PUBLIC_SHARES
    R->>-C: DKG_PUBLIC_SHARES (xT)
```

**Comment by xoloki** [comment]
Just wanted to say how awesome it was to have flow diagrams!

**Comment by netrome** [comment]
> FYI Github supports mermaid.js diagrams: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams...

Amazing! I'll use that next time. For these charts, I used [asciiflow](https://asciiflow.com/#/), with some final touches directly in my [text editor](https://github.com/netrome/helix).

**Comment by netrome** [comment]
> Amazing! I'll use that next time. For these charts, I used [asciiflow](https://asciiflow.com/#/), with some final touches directly in my [text editor](https://github.com/netrome/helix).

Edit: I updated this issue now with mermaid charts.

**Comment by xoloki** [comment]
The charts look amazing!
