### ISSUE TITLE
2.1: Affirmation logic in burnchains::db panics due to burnchain fork

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3520]
The assertion at https://github.com/stacks-network/stacks-blockchain/blob/develop/src/burnchains/db.rs#L732 can cause a panic in certain burnchain forks. This was seen in Hiro's 2.1 testnet node. It was running an old build, but this bug is present in `develop` as well.

Relevant portion of the stack trace:

```
Process abort due to thread panic: panicked at 'assertion failed: `(left == right)`   left: `42`,  right: `44`', src/burnchains/db.rs:729:9

Panic backtrace:    0: stacks_node::main::{{closure}}
              at src/testnet/stacks-node/src/main.rs:59:18
    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
...
    7: core::panicking::assert_failed
              at rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:203:5
    8: blockstack_lib::burnchains::db::BurnchainDBTransaction::make_reward_phase_affirmation_map
              at src/src/burnchains/db.rs:729:9
    9: blockstack_lib::burnchains::db::BurnchainDBTransaction::update_block_descendancy
              at src/src/burnchains/db.rs:469:21
    10: blockstack_lib::burnchains::db::BurnchainDBTransaction::store_blockstack_ops
              at src/src/burnchains/db.rs:901:9
```

After a little digging it seems this was caused by a burnchain fork at height 2417545

```sql
sqlite> select block_hash from burnchain_db_block_headers where block_height = 2417545;
000000000000000b50b99180deeea0f92a379cd65414df4af02dc74707e7306d
000000003126084450b3872ec609055f986c48a300accc230a8340923c86c29b
```

There's two blocks there, and each of them include 2 stacks operations:

```sql
sqlite> SELECT txid FROM burnchain_db_block_ops WHERE block_hash = "000000003126084450b3872ec609055f986c48a300accc230a8340923c86c29b";
c0814b6585386f3b100fb8870c2cbeb3ba27f0fbfe7b8b183d146625a2c5363c
042e1a4b49926c963f6661dcf575308e51e969166a35ff9e0364677dc3dc23f6
sqlite> SELECT txid FROM burnchain_db_block_ops WHERE block_hash = "000000000000000b50b99180deeea0f92a379cd65414df4af02dc74707e7306d";
c0814b6585386f3b100fb8870c2cbeb3ba27f0fbfe7b8b183d146625a2c5363c
042e1a4b49926c963f6661dcf575308e51e969166a35ff9e0364677dc3dc23f6
```

However, those txids have different vtx indexes in the two forks -- the relevant difference is that in one fork it is 44 and the other it is 42.

So how does `make_reward_phase_affirmation_map()` end up with an arg from one fork and an arg from the other fork? In `update_block_descendancy`, `get_commit_at` is invoked, which invokes `get_commit_in_block_at`. This method selects the txid from `block_commit_metadata` table, and then uses the txid to lookup in the `burnchain_db_block_ops` table. However, txid by itself cannot differentiate between the two versions of the transaction that appears in the block ops table (in both forks, the txid is the same, but the vtxindex is different).

One "quick fix" would be to add the burnchain header hash to that last lookup, but I'm wondering if this is surfacing a different issue for the affirmation logic in burnchains::db.

**Comment by kantai** [comment]
Pinging @jcnelson for input

**Comment by jcnelson** [comment]
> One "quick fix" would be to add the burnchain header hash to that last lookup, but I'm wondering if this is surfacing a different issue for the affirmation logic in burnchains::db.

I think this is the actual fix.  The issue is that the `indexer` argument (something that implements `BurnchainHeaderReader`) to `update_block_descendancy` is supposed to be used to identify the canonical block history.  But, it's not being used here.  The burnchain DB doesn't ever forget block data, so it's entirely possible that a block-commit can get mined in two different blocks.  This would mean that `get_block_commit()` is broken -- it could return a block-commit that doesn't exist in the canonical fork.

I'll work on a fix.
