### ISSUE TITLE
[eng quality] standardize import order

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#3539]
Proposing that we update import order such that each file uses three groupings:
- std/alloc/core
- external crate import
- imports from inside crate (self, super, crate)

**Comment by jcnelson** [comment]
What's the command for doing this?

**Comment by jcnelson** [comment]
@pavitthrap to also update the CI `rust fmt` step to enforce this.

**Comment by diwakergupta** [comment]
https://rust-lang.github.io/rustfmt/?search=&version=v1.5.1#group_imports

**Comment by pavitthrap** [comment]
fixed by #3556
