### ISSUE TITLE
Add burn ops RPC for PegOut

### ISSUE THREAD

**Issue by igorsyl** [stacks-network/stacks-blockchain#3553]
Refer to PegIn https://github.com/stacks-network/stacks-blockchain/pull/3511

**Comment by stjepangolemac** [comment]
@igorsyl the PR that added this RPC has been merged. Is that enough to close this one or do we need some additional testing?

I've been unable to find any tests that go through the API to make sure new RPCs are exposed. I suppose adding such a test for this PR is not needed then.

**Comment by igorsyl** [comment]
@stjepangolemac Yes, but the PR title needs to be more accurate. I updated it to reflect that it's RPC and not just wire format. Also, let's try to make PRs smaller when it's possible.

**Comment by igorsyl** [comment]
@stjepangolemac please use this PR to add proper tests to core-eng. Thanks!
https://github.com/stacks-network/stacks-blockchain/pull/3511

**Comment by igorsyl** [comment]
> We might not be referring to the same thing but I believe we've already added tests such as those from the linked PR.
> 
> They've all been moved to this new file: https://github.com/stacks-network/stacks-blockchain/blob/next/src/chainstate/burn/operations/test/serialization.rs#L430
> 
> Are those tests the ones you were looking for?

@kantai is this properly tested?

**Comment by kantai** [comment]
Yes, it is. Those tests are fixture/test-vector style tests which assert that the RPC _formatting_ is correct, and then there's assertions in https://github.com/stacks-network/stacks-blockchain/blob/next/testnet/stacks-node/src/tests/neon_integrations.rs#L11103 that check the integration with the rest of the node.
