### ISSUE TITLE
[sBTC] Make sBTC burnchain operations observable from the event observer

### ISSUE THREAD

**Issue by netrome** [stacks-network/stacks-blockchain#3554]
Following the introduction of peg-in and peg-out operations in #3486 and #3510 we should make these operations available through the event observer.

**Comment by igorsyl** [comment]
Let's add new issues here to the "sBTC Alpha" as well.
https://github.com/orgs/Trust-Machines/projects/5

**Comment by jcnelson** [comment]
Temporarily assigning this to @netrome so it has an owner.  Please feel free to re-assign!

**Comment by netrome** [comment]
Great! I'm not super familiar with the event observer. Is this something we need for sBTC? Otherwise we can close this for now, and add the events when we have a use case for them.

Ping @igorsyl @jcnelson

**Comment by kantai** [comment]
Adding the burnchain data for sBTC burnchain ops to this function

https://github.com/stacks-network/stacks-blockchain/blob/8d7ce23c49b96f86aa3433dc271809be4f17bda8/src/chainstate/burn/operations/mod.rs#L638

Should be sufficient for the event observer to broadcast the events. As long as any additional burnchain ops get added to that function, I think this issue should be handled.

**Comment by igorsyl** [comment]
cc @zone117x

**Comment by netrome** [comment]
Looking at the code now, the burnchain data seems to have been added already by @stjepangolemac when he added the RPC endpoints. Therefore, the events should already be broadcasted on next. I'll close this ticket, @zone117x feel free to reopen if you can't observe the events on next.
