### ISSUE TITLE
[chore] Bump version of docker/login-action 

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#3559]
The CI workflow invokes `docker/login-action@v1`. Running this action triggers the following warning: 
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

We should switch to v2 of this action, which addresses this warning. The [changelog](https://github.com/docker/login-action/releases/tag/v2.1.0) of the latest version of the action bumps the version of `@actions/core`, which fixes the issue.

**Comment by wileyj** [comment]
this was addressed in #3199
