### ISSUE TITLE
More flexibility with constants

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3562]
Clarity does not allow constants to be used in some places that require literals, but there does not seem to be a good reason for this limitation. For example:

```
(define-constant my-max-len u100)
(define-data-var my-list (list 100 uint) (list ))
(as-max-len? (var-get my-list) max-len)
```

Similar changes were made in 2.1 to allow principal constants to be used in more places. This should be expanded.

_Thanks for the report from BowTiedDeployer on Discord_

**Comment by jcnelson** [comment]
This will be part of @obycode's typechecker rewrite

**Comment by jcnelson** [comment]
Tentatively assigning to @obycode so it as an owner.  Feel free to pass along!

**Comment by obycode** [comment]
I'll enthusiastically accept assignment of all Clarity issues 😄.

**Comment by obycode** [comment]
I found this stale similar issue: #1638.

**Comment by obycode** [comment]
Let's actually close this one and re-open that one because it has some more context. I will add the details from this one there.
