### ISSUE TITLE
clarity as-max-len?

### ISSUE THREAD

**Issue by downtownallday** [stacks-network/stacks-blockchain#3571]
clarity-cli from 2.1.0.0.0-rc4

unless you give a literal to the second argument to as-max-len? it seems to fail

these examples are using repl:

> (as-max-len? "xxx" (- u6 u3))
Type check error:
TypeError(UIntType, UIntType)
Near:
[SymbolicExpression { expr: List([SymbolicExpression { expr: Atom(ClarityName("as-max-len?")), id: 2, span: Span { start_line: 1, start_column: 2, end_line: 1, end_column: 12 } }, SymbolicExpression { expr: LiteralValue(Sequence(String("xxx"))), id: 3, span: Span { start_line: 1, start_column: 14, end_line: 1, end_column: 18 } }, SymbolicExpression { expr: List([SymbolicExpression { expr: Atom(ClarityName("-")), id: 5, span: Span { start_line: 1, start_column: 21, end_line: 1, end_column: 21 } }, SymbolicExpression { expr: LiteralValue(UInt(6)), id: 6, span: Span { start_line: 1, start_column: 23, end_line: 1, end_column: 24 } }, SymbolicExpression { expr: LiteralValue(UInt(3)), id: 7, span: Span { start_line: 1, start_column: 26, end_line: 1, end_column: 27 } }]), id: 4, span: Span { start_line: 1, start_column: 20, end_line: 1, end_column: 28 } }]), id: 1, span: Span { start_line: 1, start_column: 1, end_line: 1, end_column: 29 } }]

> (as-max-len? "xxx" (to-uint (- 6 3)))
Type check error:
TypeError(UIntType, UIntType)

> (as-max-len? "xxx" u3)
(some "xxx")

clarity-cli repl also panics but am not including that here.

**Comment by obycode** [comment]
This is expected behavior. Note the description (emphasis added):
> The as-max-len? function takes a sequence argument and a uint-valued, **literal** length argument.

Issue #3350 discusses improving the error message for this.
