### ISSUE TITLE
Local stack-node mocknet crashes on `next`

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/stacks-blockchain#3581]
**Describe the bug**
When I try to run the `stacks-node` in `mocknet` mode locally it panics with the error below.

```
INFO [1676995868.300836] [src/chainstate/stacks/db/mod.rs:1552] [main] Computed Clarity state genesis, root_hash: a1cd6e702a1b103289eb5cb3a278ab21f4b1c8529bd81d235daa6ec9bf5c77ba
ERRO [1676995868.446158] [testnet/stacks-node/src/main.rs:58] [main] Process abort due to thread panic: panicked at 'FATAL: no epoch 2.1 defined', testnet/stacks-node/src/config.rs:463:14
```

**Steps To Reproduce**
`cargo run --bin stacks-node -- mocknet`

**Expected behavior**
Local mocknet running without issues.

**Environment (please complete the following information):**
 - OS: MacOS
 - Rust version: 1.67.1
 - Version of the appropriate binary / software package: `next` branch

**Comment by jcnelson** [comment]
This is probably a dup of https://github.com/stacks-network/stacks-blockchain/issues/3366

**Comment by stjepangolemac** [comment]
To be honest I hardly remember what this one was about. I'll try to reproduce this now in case it was fixed.

**Comment by stjepangolemac** [comment]
It's not crashing for me locally now. Let's consider it fixed for now.
