### ISSUE TITLE
Benchmarks are not up to date

### ISSUE THREAD

**Issue by stjepangolemac** [stacks-network/stacks-blockchain#3584]
**Describe the bug**
The `benches/` directory contains nonfunctional code, there's something like 50-60 errors that my LSP is detecting.

**Steps To Reproduce**
Run `rust-analyzer` directly or through an editor on the whole repo.

**Expected behavior**
Repo is free from LSP errors and warnings.

If we want to do something about this I see two options:

- bring the benchmarks up to date and fix all problems
- delete the directory

**Comment by igorsyl** [comment]
Can we keep the code but detach or ignore it from the build tree?

**Comment by stjepangolemac** [comment]
There's an `exclude` option in `Cargo.toml` when dealing with workspaces but it doesn't work with benchmarks. They're not even an explicit part of the workspace.

I've tried a few things and this seems to work:

1. Rename all bench files to `*.rs.backup`
2. Remove `[[bench]]` entries from `Cargo.toml`

This makes sure that rust-analyzer will ignore those files, but we still have them there in case we want to fix them up. I'll create a draft PR where we can discuss it.

**Comment by igorsyl** [comment]
I support this, but I suspect @kantai may not like the idea of stale code.

**Comment by jcnelson** [comment]
I think it's fine to remove code that no longer works.  It's already in the git history.  @kantai we're not relying on this now or in the near-term, right?
