### ISSUE TITLE
Error when starting Stacks Node Error with Bitcoin Node synced 77%

### ISSUE THREAD

**Issue by BowTiedDeployer** [stacks-network/stacks-blockchain#3588]
**Describe the bug**
Started to sync Bitcoin node mainnet.
When at 77%, tried to start the Stacks node mainnet.
Before downloading the BTC block headers or anything else, it split the following error:

```
WARN [1677421413.559267] [src/burnchains/burnchain.rs:694] [main] Failed to stat burnchain DB path '/home/ubuntu/stacks-blockchain/data/mainnet/burnchain/burnchain.sqlite': Os { code: 2, kind: NotFound, message: "No such file or directory" }
ERRO [1677421413.577888] [testnet/stacks-node/src/main.rs:58] [main] Process abort due to thread panic: panicked at 'index out of bounds: the len is 0 but the index is 0', src/burnchains/bitcoin/spv.rs:834:33
ERRO [1677421413.618335] [testnet/stacks-node/src/main.rs:60] [main] Panic backtrace:    0: stacks_node::main::{{closure}}
             at testnet/stacks-node/src/main.rs:59:18
```

**Steps To Reproduce**
Download bitcoin 24.0.1
```
wget https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz
```
Create the bitcoin.conf for the mainnet node. 
Start bitcoin core
```
./bitcoind -conf=/home/ubuntu/bitcoin-24.0.1/bitcoin.conf
```

Clone `master` branch stacks repo
```
git clone https://github.com/stacks-network/stacks-blockchain.git
```
Compile node
```
cargo build --features monitoring_prom,slog_json --release --bin stacks-node
```
Run compiled node

**Expected behavior**
I expect it to start downloading the headers, and then sync with the bitcoin node progress.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Rust version `rustc 1.61.0`
 - Version of the appropriate binary / software package 
   - bitcoin node `24.0.1`
   - stacks node branch master

**Comment by jcnelson** [comment]
Yup, looks like bug.  Got a mitigation: #3589.

**Comment by jcnelson** [comment]
This particular issue is fixed in `develop`.
