### ISSUE TITLE
It takes 2 weeks or more for a node to synchronize blocks from 0. Is there any way to speed it up?

### ISSUE THREAD

**Issue by blocknodehub** [stacks-network/stacks-blockchain#3630]

**Comment by igorsyl** [comment]
@blocknodehub https://docs.hiro.so/references/hiro-archive

**Comment by wileyj** [comment]
@blocknodehub this is the wrong repo for the issue, but it's something i'm working on scripting. 
the crux of it is that v7 of the API uses a lot more IO on postgres than previous versions, and if you run all services on the same machine you enter a cpu wait mode so the entire sync is much slower. 

using the archiver is @igorsyl linked is the correct solution, once i have a fully tested script to download/import the data i'll link it

**Comment by wileyj** [comment]
@blocknodehub https://github.com/stacks-network/stacks-blockchain-docker/blob/master/scripts/seed-chainstate.sh

depending on how you're running the API/postgres you'll want to make some adjustments but the above works in the framework of that repo
