### ISSUE TITLE
[mining] Stop awarding coinbases for non-empty sortitions 

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-blockchain#3653]
Right now, if there are _B_ Bitcoin blocks between Stacks blocks _S_ and _S+1_, the winner of _S+1_ receives _B_ coinbases.  The rationale for this is to ensure that mining is always eventually profitable as long as the value of STX is positive -- the accumulating STX coinbases will eventually exceed the value of the Bitcoin transaction fee.

The problem with this naive approach is that it **makes block-orphaning profitable** for a coalition of miners with a majority of the mining power.  The current rules will award the orphaned blocks' coinbases to the coalition on the coalition's fork, meaning that there's no (non-trivial) cost to orphaning blocks.

I think this is easily fixed: **only award missing coinbases for Bitcoin blocks with no sortition**.  This addresses the aforementioned problem of ensuring that the chain remains live in the face of wild STX/BTC price fluctuations, while also ensuring that the act of orphaning a block is more costly than building atop it.

I don't think we need to consider whether or not a sortition has a corresponding Stacks block; just looking for whether or not a sortition happened is enough.  Since we're assuming that miners are economically rational, then I think we can assume that, on the whole, people who send block-commit transactions (which aren't free) are intending to append Stacks blocks.

**Comment by Ston3cutt3r** [comment]
>The current rules will award the orphaned blocks' coinbases to the coalition on the coalition's fork, meaning that there's no (non-trivial) cost to orphaning blocks.

Unfortunately, that is not correct? There are no rewards for orphaned blocks. These rewards are "lost" and don´t get arwarded to anyone at the moment.

Please prove me wrong, but let´s have a look at BTC block 784019-784023 as an example. In this range of five blocks there is one block without a sortition (784019) and four blocks (784020-784023) are orphaned. Nevertheless, the entity who initiated the fork only won 1000 STX coinbase rewards with BTC block 784024 / Stacks block 100943.

By initiating these forks the entity is able to "bleed out" other miners. But don´t get a direct reward.

**Comment by jcnelson** [comment]
Yes, you are correct @Ston3cutt3r.  Looking at the code, a Stacks block does not accumulate a coinbase for a Bitcoin block in which a sortition occurred (regardless of whether or not it is on the same fork).  It only accumulates them if there was no sortition winner, so this issue as described can be closed.

However, this fact would mean that orphaning blocks is _already_ less cost-effective than confirming them.  The economically rational thing to do is to confirm blocks, since it minimizes the BTC spend per STX earned.
