### ISSUE TITLE
Stacker endorsement lookup from Sortition DB

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3666]
To support validation of stacker endorsement messages, the SortitionDB needs to be able to invoke the read-only method `check-stacked-by-key` in the `pox-endorsement` contract (see #3665) from the current anchor block (if there is a current anchor block).

This means that the SortitionDB will need to be able to establish `StacksChainState` connection.

This issue will cover introducing the new lookup routine in the SortitionDB, testing the routine, and verifying that it does not introduce a dead-lock condition between the SortitionDB and StacksChainstate.

### Alternative

As an alternative scheme, the sortition DB can attempt to track the endorsement key state by itself (much like it currently tracks reward set state).

At the start of a PoX reward cycle, the `stacks-node` computes the set of active stackers by consulting the PoX anchor block and writing this information into the sortition DB. To support Stacker endorsement  key tracking, the sortition DB would *also* track the endorsement-keys for Stackers.

This would extend the current reward-set calculation with the following steps:

1. For each entry in the reward set, if an early-unlock was not issued, read the `stacker` field
2. For each `stacker` field which is `some`, consult the `pox-endorsement` contract for the associated endorsement key.
3. Add a `<reward-cycle-number>.<endorsement-public-key-hex>` key with value `<stacked-amount>` to the sortition DB MARF.

Unfortunately, this scheme does _not_ allow for the tracking of delegated stackers. This is because reward-set entries created by delegates set the `stacker` field to `none`. Furthermore, tracking _any_ possible delegated stacker would require unbounded (or a very very high bound) amount of state: delegated stackers can be arbitrarily small.

**Comment by jcnelson** [comment]
I'm not sure that this coupling is strictly necessary? What if there was
instead a static method that just took a ref to both the chainstate and
sortition DB handles?

Maybe it would be helpful to enumerate the call sites for this lookup?  On
the block validation path, endorsement lookup only happens on block-commit
validation, right? On the mining path, it additionally happens in the code
that selects which chain tip to build atop (i.e. the default behavior could
be to build on the highest endorsed tip). Can you think of others?

**Comment by kantai** [comment]
Closing this -- the design of nakomoto has changed and this issue is no longer relevant.
