### ISSUE TITLE
Stacker endorsement validation

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3667]
As part of the fork rules proposed in SIP-021, Stacks consensus rules will only allow block commits to build off of blocks that are <= 6 blocks deep **or** are <= 100 **Bitcoin** blocks deep _and_ the block is endorsed by Stackers. 

This issue covers the validation of Stacker endorsement messages.

An endorsement message is valid iff:

1. The block that it references is a winning block hash (i.e., it won its sortition)
2. The endorsement is signed by a public key contained within the current PoX cycle's "peg wallet key" set.

Once validated, the endorsement should insert a row in a new table in the SortitionDB with the amount of STX associated with the endorsement.

Validation needs to be able to perform endorsement key lookups (see #3666)

**Comment by jcnelson** [comment]
While the sortition DB will need to store _all_ endorsements it processes
(across all PoX forks), I don't think it needs to track which ones are
valid?

I strongly suspect that the work of tracking valid endorsements will fall
to the chains coordinator, not the sortition DB. The question of whether or
not an endorsement tx is valid cannot be answered without also knowing
which Stacks fork (and thus PoX fork) it was meant for. So, we would track
all valid endorsements within all Stacks forks and report the system-wide
endorsement as the one on the canonical Stacks fork.

**Comment by kantai** [comment]
> While the sortition DB will need to store _all_ endorsements it processes (across all PoX forks), I don't think it needs to track which ones are valid?

This would be necessary for the sortition db to reject block commits that try to execute a middle fork (i.e., `6 < depth < 100`) before considering them for sortition wins. The sortition db would need to be able to at least track which block commits are _endorsed_.

> I strongly suspect that the work of tracking valid endorsements will fall to the chains coordinator, not the sortition DB.

It's possible that the chains coordinator could interpose on this, like it does for computing reward sets, but it would need to do so on every burn block (so I'm not sure that there's much advantage there).

> The question of whether or not an endorsement tx is valid cannot be answered without also knowing which Stacks fork (and thus PoX fork) it was meant for. So, we would track all valid endorsements within all Stacks forks and report the system-wide endorsement as the one on the canonical Stacks fork.

Is that strictly necessary? The endorsement transaction points at a block commit, but the endorsement transaction is evaluated within the context of the active reward cycle. If there _is_ an active reward cycle, then because of #3664, there is no more PoX fork possible -- the active reward cycle is the only consensus option. That means that the sortition DB should be able to validate endorsements.

**Comment by kantai** [comment]
Closing this -- the design of nakomoto has changed and this issue is no longer relevant.
