### ISSUE TITLE
Enable PoX-3 

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-blockchain#3681]
Central issue to track all activities for enabling PoX-3 [[Ref](https://discord.com/channels/621759717756370964/730814571517968436/1100069134223552612)]

1. (in review: #3688) Add epoch transition method for 2.2 -> 2.3, which instantiates pox-3 
1. (Done in feat/epoch-2.3)Add LockedPoxThree variant for StxAccount
1. (in review: #3697) Add clarity_vm::special handlers for pox-3 which apply LockedPoxThree locks
1. Correct the `stack-increase` bug (Brice will add to #3689)
1. Add `delegated-to` field to `stacking-state` - #3689
1.  Add checks to all delegate public methods to ensure that the `stacking-state` entry either: #3689 (in progress)
      a. doesn't exist, if creating a new lockup
      b. exists and matches the delegate in `delegate-extend` or `delegate-increase`

1. Add checks to all solo stacking methods to ensure that the `stacking-state` entry either: #3689 (in progress)

   a. doesn't exist, in the case of `stack-stx`

   b. exists, and has `delegated-to` set to None.
1. Make sure pox-3 naming changes occur in pox-3.clar (ex: replace `2-1-reward-cycle` references with `pox-3-reward-cycle`)

1. Add Epoch 2.3
1. Alter the pox-selection flags from 2.2 to check when 2.3 activates and use pox-3
2. (in review: #3697) There are special handlers for pox-2 functions which emit events that the API consumes, these events must be emitted for pox-3 as well. 
1. (in review: #3704) Add `.pox-3` to `contract_versions` in `/v2/pox` RPC response
1. (in review: #3705) Epoch 2.2 through 2.4 should be configurable in regtest (krypton/neon) mode via toml file

**Comment by kantai** [comment]
Branch for ongoing work:

https://github.com/stacks-network/stacks-blockchain/tree/feat/epoch-2.3

So far, it introduces Epoch 2.3 and defines the `STXBalance::LockedPoxThree` variant

**Comment by obycode** [comment]
WIP PR that covers 5, 6, and 7: #3689

**Comment by zone117x** [comment]
Can we add this to the list?
```
Add `.pox-3` to `contract_versions` in `/v2/pox` RPC response`
```

This is critical for tooling like stacks.js and the API to determine which pox contract version to use when constructing stacking transactions.

**Comment by friedger** [comment]
pox-3 is live and enabled.
