### ISSUE TITLE
resolve microblock duplicate public keys

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-blockchain#3707]
https://discord.com/channels/621759717756370964/730814571517968436/1104082430794661958

majority of miners are not mining microblocks due to `occasionally get slashed due to duplicate public keys` (copypasta from above discord link). 

post 2.4 work, we should investigate how to resolve this so microblocks can be enabled again by all miners. 

Further, the log messages are unclear when this happens:

```json
{"msg":"Failed to apply tx db836f3299f858c67828f8fdbaa9f069a6d31d6b81b357e93eb50d4db4448e53: InvalidStacksTransaction(\"Invalid transaction anchor mode for anchored data\", false)","level":"WARN","ts":"2023-05-05T14:59:25.065269932Z","thread":"miner-block-http://0.0.0.0:20443","line":2571,"file":"src/chainstate/stacks/miner.rs"}
```

```json
{"msg":"Tx processing skipped","level":"INFO","ts":"2023-05-05T14:59:25.354876025Z","thread":"miner-block-http://0.0.0.0:20443","line":390,"file":"src/chainstate/stacks/miner.rs","reason":"Stacks transaction skipped during assembly due to: Transaction already considered.","event_type":"skip","tx_id":"db836f3299f858c67828f8fdbaa9f069a6d31d6b81b357e93eb50d4db4448e53","event_name":"transaction_result"}
```

```json
{"msg":"Tx processing skipped","level":"INFO","ts":"2023-05-05T14:59:51.680616217Z","thread":"miner-microblock-http://0.0.0.0:20443","line":390,"file":"src/chainstate/stacks/miner.rs","reason":"Stacks transaction skipped during assembly due to: BlockLimitFunction::LIMIT_REACHED","event_type":"skip","tx_id":"db836f3299f858c67828f8fdbaa9f069a6d31d6b81b357e93eb50d4db4448e53","event_name":"transaction_result"}
```

**Comment by kantai** [comment]
These log messages mean three different things:

1. The miner isn't applying a transaction in an anchor block because the transaction is set to only be mined in a microblock.
2. A transaction isn't being applied because the transaction was already attempted during the current block assembly
3. A transaction isn't being applied because the block execution limit has been reached

**Comment by jcnelson** [comment]
Related issue:
https://github.com/stacks-network/stacks-blockchain/issues/3620

In light of this issue, I advised miners to not mine microblocks for the
time being.

**Comment by wileyj** [comment]
> These log messages mean three different things:
> 
> 1. The miner isn't applying a transaction in an anchor block because the transaction is set to only be mined in a microblock.
> 2. A transaction isn't being applied because the transaction was already attempted during the current block assembly
> 3. A transaction isn't being applied because the block execution limit has been reached

i understood a little better after looking at the code - i guess what my ask would be here is that the logs could be a little more clear about what's happening. i'm not sure what's better without making the log more verbose, but looking at the logs only was a bit confusing. 

2 was prety clear to be honest, but 3 i'm still having a hard time understanding - i couldn't find where a limit is set for `BLOCK_LIMIT`,but i'm not sure that changing the log would be more helpful
