### ISSUE TITLE
stacks-blockchain fails to start on 2.3.0.0.0

### ISSUE THREAD

**Issue by pseudozach** [stacks-network/stacks-blockchain#3709]
I updated bootstrap node in testnet/Config.toml to
`bootstrap_node="029266faff4c8e0ca4f934f34996a96af481df94a89b0c9bd515f3536a95682ddc@seed.testnet.hiro.so:20444"`

I was running testnet node 2.1.0.0.0 with stacks-blockchain-docker and updated blockchain version to 2.3.0.0.0 and restarted everything and now node will not start with this error:

>stacks-blockchain      | ERRO [1683435340.687294] [testnet/stacks-node/src/main.rs:58] [main] Process abort due to thread panic: panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to lookup address information: Try again" }', testnet/stacks-node/src/config.rs:1780:51
stacks-blockchain      | ERRO [1683435340.835810] [testnet/stacks-node/src/main.rs:60] [main] Panic backtrace:    0: stacks_node::main::{{closure}}
stacks-blockchain      |              at src/testnet/stacks-node/src/main.rs:59:18
stacks-blockchain      |    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
stacks-blockchain      |       std::panicking::rust_panic_with_hook
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
stacks-blockchain      |    2: std::panicking::begin_panic_handler::{{closure}}
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
stacks-blockchain      |    3: std::sys_common::backtrace::__rust_end_short_backtrace
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
stacks-blockchain      |    4: rust_begin_unwind
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
stacks-blockchain      |    5: core::panicking::panic_fmt
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
stacks-blockchain      |    6: core::result::unwrap_failed
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
stacks-blockchain      |    7: core::result::Result<T,E>::unwrap
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1090:23
stacks-blockchain      |       stacks_node::config::NodeConfig::add_bootstrap_node
stacks-blockchain      |              at src/testnet/stacks-node/src/config.rs:1780:24
stacks-blockchain      |       stacks_node::config::NodeConfig::set_bootstrap_nodes
stacks-blockchain      |              at src/testnet/stacks-node/src/config.rs:1794:17
stacks-blockchain      |    8: stacks_node::config::Config::from_config_file
stacks-blockchain      |              at src/testnet/stacks-node/src/config.rs:895:13
stacks-blockchain      |    9: stacks_node::main
stacks-blockchain      |              at src/testnet/stacks-node/src/main.rs:187:22
stacks-blockchain      |   10: core::ops::function::FnOnce::call_once
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
stacks-blockchain      |       std::sys_common::backtrace::__rust_begin_short_backtrace
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:134:18
stacks-blockchain      |   11: std::rt::lang_start::{{closure}}
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:166:18
stacks-blockchain      |   12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
stacks-blockchain      |       std::panicking::try::do_call
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
stacks-blockchain      |       std::panicking::try
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
stacks-blockchain      |       std::panic::catch_unwind
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
stacks-blockchain      |       std::rt::lang_start_internal::{{closure}}
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
stacks-blockchain      |       std::panicking::try::do_call
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
stacks-blockchain      |       std::panicking::try
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
stacks-blockchain      |       std::panic::catch_unwind
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
stacks-blockchain      |       std::rt::lang_start_internal
stacks-blockchain      |              at rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
stacks-blockchain      |   13: main
stacks-blockchain      | 
stacks-blockchain      | Dumping core for pid 1
stacks-blockchain exited with code 0

**Comment by obycode** [comment]
If you were running 2.1 into the 2.2 epoch, then you may have a corrupt chain state. To resolve, you'd need to re-sync from genesis or start with a snapshot.

**Comment by pavitthrap** [comment]
This has been resolved.
