### ISSUE TITLE
Change Clarity case testing 

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#3720]
Right now, we use the `rstest` library to enable us to create templates. These templates allow us to run the same test for different clarity versions & Stacks epochs. Ex:
```
#[template]
#[rstest]
#[case(ClarityVersion::Clarity1, StacksEpochId::Epoch2_05)]
#[case(ClarityVersion::Clarity1, StacksEpochId::Epoch21)]
#[case(ClarityVersion::Clarity2, StacksEpochId::Epoch21)]
...
fn test_edge_counting_runtime_template(
    #[case] version: ClarityVersion,
    #[case] epoch: StacksEpochId,
) {
}
```

When we add new epochs, there's no verification check to ensure the new epoch cases are added to each of these `rstest` uses. We currently manually add it. We should make a change such that this is checked programatically.

**Comment by kantai** [comment]
Completely agreed. I think this should be paired with a general rstest update (the version we use makes use of some deprecated rust features) and cleanup: we should not need to redefine the template continuously as we do now, and should be able to just define the template once and then import the macro.
