### ISSUE TITLE
UTXO lookup uses parent block height, but should use current block height instead

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3733]
**Describe the bug**

The bitcoin_regtest_controller used to submit block commit operations looks up UTXOs in a buggy way which can lead to the miner submitting multiple concurrent commits in certain circumstances (we're seeing this on testnet due to the deep testnet reorg).

https://github.com/stacks-network/stacks-blockchain/blob/master/testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs#L1158-L1165

This should use the current burn block height instead.

**Comment by wileyj** [comment]
Confirmed this branch is able to mine some blocks on a testnet fork

**Comment by pavitthrap** [comment]
Handled in #3738
