### ISSUE TITLE
A contract deploy with an error should fail

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-blockchain#3740]
**Describe the bug**
If a contract deploy has a top level error, this should cause the reply transaction to fail. Currently, the transaction result shows as  `(ok true)`, appearing to be a successful deploy, but the contract, correctly, is not actually deployed.

**Steps To Reproduce**
Deploy a contract that will trigger a top-level error. A simple example is:

```clarity
(try! (if false (ok true) (err u1)))
```

**Expected behavior**
I expect this transaction to fail, but it shows like a successful deploy. See https://explorer.hiro.so/txid/0xfdc2383bec744633da382b8fd8414cd74ca81a7b27c93ac495e3b4e0587a2990?chain=testnet for an example. The transaction appears to be successful, but we can see that the contract is not actually deployed by the 404 here - https://api.hiro.so/extended/v1/contract/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM/prior-amethyst-pelican.

**Comment by friedger** [comment]
The contract is available at https://api.testnet.hiro.so/extended/v1/contract/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.prior-amethyst-pelican

**Comment by obycode** [comment]
Oops! 🤦 . Thanks @friedger. I guess then I was just wrong about the error at the top-level causing the deployment to fail.

**Comment by obycode** [comment]
Yeah, I'm interested in digging in deeper on this too, but closed the issue for now since my initial assumption was wrong.

**Comment by friedger** [comment]
@obycode related discussion https://github.com/stacks-network/stacks-blockchain/issues/3154
