### ISSUE TITLE
Add RPC API method to read a data-var

### ISSUE THREAD

**Issue by igorsyl** [stacks-network/stacks-blockchain#3747]
**Is your feature request related to a problem? Please describe.**
Node has endpoint `map_entry` to read values from a map.
I am not aware of a method to read the value of a data-var.

**Describe the solution you'd like**
@radicleart pointed our need for a similar endpoint `data_entry` (or similar name) to read the value of `data-var`.

**Describe alternatives you've considered**
Copy paste values from Hiro Explorer.

**Additional context**
Requested by @radicleart

**Comment by igorsyl** [comment]
Ah great! Is this exposed in the API? @saralab

**Comment by obycode** [comment]
> Which API? The stacks-blockchain-api simply proxies _all_ RPC endpoints exposed by `stacks-node` (so basically anything starting with `/v2/...`), so the get data-var endpoint is already supported:

The confusion here might be because our API documentation includes some but not all of these `/v2/` endpoints, and this `data_var` is not in there. @zone117x is there a reason for that or could we add any missing endpoints?

**Comment by zone117x** [comment]
> @zone117x is there a reason for that or could we add any missing endpoints?

A couple years ago, only the Hiro stacks-blockchain-api repo had the OpenAPI spec for these endpoints. They are only still around in the api repo to avoid breaking a few things, but ideally the repo would no longer include them at all.

**Comment by obycode** [comment]
I agree, it would make sense to remove them completely from the API repo, so that those docs are maintained with their source. From a user standpoint though, I would want one place to go to to find all of these endpoints. Could we do that in our API documentation page? Are the docs for the /v2 endpoints published anywhere now, outside of the ones in the API repo?
