### ISSUE TITLE
Bug: miner address could change across 2.1 epoch boundary

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-blockchain#3789]
In `bitcoin_regtest_controller.rs`, there is a function called `get_miner_adsress` that generates a BitcoinAddress given the epoch and public key. 

Here is the main body of that function 
```
if self.config.miner.segwit && epoch_id >= StacksEpochId::Epoch21 {
            let hash160 = Hash160::from_data(&public_key.to_bytes_compressed());
            BitcoinAddress::from_bytes_segwit_p2wpkh(network_id, &hash160.0)
                .expect("Public key incorrect")
        } else {
            ...
        }
```

If self.config.miner.segwit is true, and it is before the Epoch 2.1 boundary, the else clause is active, and after the boundary is crossed, the if clause will be active. Thus, the same miner address can have two different representations in the Stacks node, which is surprising behavior.

**Comment by jcnelson** [comment]
This behavior is deliberate.  It allows miners to automatically convert to segwit as the network upgrades if they so choose.
