### ISSUE TITLE
Nakamoto: Event interface for StackerDB notifications

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3856]
To avoid any need to perform a polling loop, binaries like the block
producer and stacker signer need to be able to receive push
notifications when relevant StackerDB data arrives in their paired
`stacks-node`.

Unless it becomes an issue for stalling (which I don't expect), this
should just use the existing event observer interface. This means
adding new events for StackerDB notifications.

**Comment by jcnelson** [comment]
This is now merged!
