### ISSUE TITLE
Nakamoto: NakamotoStacksBlock and NakamotoStacksBlockHeader structs

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3858]
NakamotoStacksBlockHeader should contain:

1. A producer signature field
2. A stacker signature field
3. A state root hash
4. A bitcoin block hash
5. The parent stacks block hash
6. A version number (u8)
7. TX merkle root (sha512/256)
8. Stacks fork length so far
9. BTC spent on this fork so far
10. VRF proof

The NakamotoStacksBlock will be struct containing the block header and
a Vec of the transactions (similar to the existing `StacksBlock` struct).

**Comment by kantai** [comment]
Per the updates to Nakomoto's block selection (#3892):

Nakamoto Stacks blocks will have a different wire format than Stacks blocks and microblocks today. In particular, the header will contain:

1. A version number
2. The length of the chain as of this tip
3. The total BTC spent producing this tip
4. The StacksBlockId of the parent Stacks block
5. The Bitcoin block hash of the Bitcoin block that triggered the start of the tenure in which they were mined
6. A recoverable ECDSA signature from the tenure’s miner
7. The root of a SHA512/256 Merkle tree constructed over all of its contained transactions
8. The SHA512/256 root hash of the MARF once all of the contained transactions are processed

As before, the Stacks blockchain will continue to calculate a consensus hash for each sortition. The StacksBlockId of a Stacks block would simply be the SHA512/256 of the block’s associated sortition’s consensus hash and the hash of the block header.

Absent from this header is the VRF proof. Instead, this information will be put into the Nakamoto Coinbase transaction.

**Comment by kantai** [comment]
That's this PR: https://github.com/stacks-network/stacks-blockchain/pull/3933

**Comment by saralab** [comment]
Closing this, merged in this PR: https://github.com/stacks-network/stacks-blockchain/pull/3933
