### ISSUE TITLE
Nakamoto: Chain State Table for Nakamoto Headers

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3859]
This is a new table in the same SQLite db as the current `StacksChainState`
block headers DB. It should be accessed through a new struct `NakamotoChainState`.
Each row of this table should store `NakamotoStacksBlockHeader` data, keyed by
`StacksBlockId`.

This should be a MARFed data store to assist with ancestor queries.

**Comment by saralab** [comment]
Closing, this has been merged in https://github.com/stacks-network/stacks-blockchain/pull/3992
