### ISSUE TITLE
Nakamoto: New DB for Nakamoto Staging Blocks

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3860]
This should be a new SQLite db which contains a table
`StagingBlocks`. This will be used to store new StacksBlocks as they
arrive without needing to block on other block processing.

**Comment by saralab** [comment]
@kantai : This was tackled in https://github.com/stacks-network/stacks-blockchain/pull/3992  iiuc, can we close this?

**Comment by saralab** [comment]
Merged as part of https://github.com/stacks-network/stacks-blockchain/pull/3992
