### ISSUE TITLE
Nakamoto: Chain State Interface for Nakamoto Block Processing

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3861]
* `store_block()` - stores a block that is signed by stackers and
   producers in staging db.
 * `append_block()` - validates and applies the transactions in a
   staged block to the clarity chainstate. Marks the block as
   processed. This should validate that the block *has no siblings*.
 * `get_staging_block(StacksBlockId)` - returns a stored block
 * `get_next_processable_block()` - returns a stored block that is
   processable
 * `is_processed(StacksBlockId)` - returns whether or not a given
   block has been processed

**Comment by saralab** [comment]
Closing, this has been merged in https://github.com/stacks-network/stacks-blockchain/pull/3992
