### ISSUE TITLE
Nakamoto: Query method for canonical Stacks block

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3862]
This is a method in the nakamoto chain state struct
`get_canonical_stacks_block()` which accepts a read-only connection to
the sortition database and uses it to help in returning the canonical
Stacks block by figuring out:

1. Given the current bitcoin tip, what is the highest bitcoin block in
   that fork that a stacks block has witnessed? (Each stacks block
   entry in the db stores the bitcoin block hash of the latest bitcoin
   block data that it witnessed, so this can be queried just using the
   nakamoto db). Note that this implicitly relies on a block
   processing guarantee: a stacks block is only processed if the
   bitcoin block hash in its header was processed by the node.
2. Query for the highest nakamoto block that witnessed that bitcoin
   block.

**Comment by saralab** [comment]
Merged as part of https://github.com/stacks-network/stacks-blockchain/pull/3992
