### ISSUE TITLE
Nakamoto: RPC method for block template request and fetch

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3865]
This will be two new RPC methods. The first submits a request to
generate a block template. The handler should simply push a
request onto the RPC handler comms channel.

The actual template assembly should be handled by a thread spawned
in the main `stacks-node` entry point. Template assembly is identical
to block assembly today (i.e., invocation of `build_anchored_block`
in the miner) except that it should produce a `NakamotoStacksBlock`.

Once assembled, the `NakamotoStacksBlock` should be relayed to the
event dispatcher on a new event interface.

**Comment by jcnelson** [comment]
I think this can be dropped.  Mining in Nakamoto happens the same way as it does with Stacks -- in the same process.
