### ISSUE TITLE
Nakamoto: Block producer binary

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3867]
This is a new binary that performs:

* Block template fetch from stacks-node (POST & GET /v3/block_template/)
* Block signing — in M1, this is just serializing a well-known value to the signature field.
* Produced block post to stacks-node (POST /v3/block/)

Note: it is important that the event observer endpoints *not* stall the `stacks-node`!

**Comment by jcnelson** [comment]
I think this can be dropped
