### ISSUE TITLE
Nakamoto: New stacks-node entry point

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-blockchain#3868]
A new entry point for `stacks-node` (switched into via `main.rs`) for
nakamoto operation. This entry point is responsible for spawning threads
and initializing communication channels.

This entry point should:

1. Start a relayer thread
2. Start a network thread (i.e., the current p2p thread but with the p2p stack disabled)
3. Start a nakamoto coordinator thread
4. Either spawn threading necessary for handling communication channels or loop on comms channels directly

**Comment by jcnelson** [comment]
Do we have to keep the old Neon node around?  Can we instead just create a top-level crate `stacks-nakamoto-node` or some such and build the node daemon from there?

**Comment by saralab** [comment]
Closing, merged as part of https://github.com/stacks-network/stacks-blockchain/pull/3933
