### ISSUE TITLE
[CI] Add clippy checks to the clarity subrepo

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-blockchain#3979]
Depends on : https://github.com/stacks-network/stacks-blockchain/issues/3935

Add clippy checks for the clarity subrepo to CI. To run clippy on ONLY clarity, use `cargo clippy -p clarity --no-deps --tests --all-features`

**Comment by obycode** [comment]
Not yet as far as I know, but I can make a PR for this. Thanks!

**Comment by obycode** [comment]
We are already running clippy on the new Clarity Wasm repo.

**Comment by obycode** [comment]
Closed with #4026.
