### ISSUE TITLE
[CI] Add clippy checks to libstackerdb subrepo

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-blockchain#4021]
Depends on : https://github.com/stacks-network/stacks-blockchain/issues/3936

Add clippy checks for the libstackerdb subrepo to CI. To run clippy on ONLY libstackerdb, use `cargo clippy -p libstackerdb --no-deps --tests --all-features`

**Comment by obycode** [comment]
Closed with #4026.
